#!/usr/bin/env python3
"""Append Batch 36-44 terms to the registry with proper TSV formatting."""

import pathlib

REG = pathlib.Path("terms/registry")
T = "\t"

CONCEPTS = [
    # Batch 36: ICF Physics & Implosion
    ("# ==== Batch 36: ICF Physics & Implosion ====",),
    (
        "convergence-ratio",
        "metric",
        "收敛比",
        "convergence ratio",
        "",
        "active",
        "Ratio of initial to final capsule radius in implosion",
    ),
    (
        "areal-density",
        "metric",
        "面密度",
        "areal density",
        "",
        "active",
        "rho-R product measuring compressed fuel areal density",
    ),
    (
        "richtmyer-meshkov-instability",
        "concept",
        "Richtmyer-Meshkov不稳定性",
        "Richtmyer-Meshkov instability",
        "RMI",
        "active",
        "Instability from shock traversing a density interface",
    ),
    (
        "ablation-front",
        "concept",
        "烧蚀前沿",
        "ablation front",
        "",
        "active",
        "Interface between ablating shell and compressed fuel",
    ),
    (
        "implosion-velocity",
        "metric",
        "内爆速度",
        "implosion velocity",
        "",
        "active",
        "Inward velocity of imploding capsule shell",
    ),
    (
        "hot-spot-ignition",
        "concept",
        "中心热斑点火",
        "hot-spot ignition",
        "",
        "active",
        "Central hot spot igniting surrounding cold fuel",
    ),
    (
        "capsule-implosion",
        "concept",
        "靶丸内爆",
        "capsule implosion",
        "",
        "active",
        "Driven inward compression of ICF capsule",
    ),
    (
        "mix-instability",
        "concept",
        "混合不稳定性",
        "mix instability",
        "",
        "active",
        "Shell-fuel interface material mixing during implosion",
    ),
    (
        "laser-energy-balance",
        "concept",
        "激光能量平衡",
        "laser energy balance",
        "",
        "active",
        "Laser energy partition and absorption efficiency",
    ),
    (
        "gain-curve",
        "concept",
        "增益曲线",
        "gain curve",
        "",
        "active",
        "ICF energy gain vs driver energy relationship",
    ),
    # Batch 37: Plasma Radiation & Spectroscopy
    ("# ==== Batch 37: Plasma Radiation & Spectroscopy ====",),
    (
        "line-radiation",
        "concept",
        "线辐射",
        "line radiation",
        "",
        "active",
        "Characteristic spectral line radiation from bound-bound transitions",
    ),
    (
        "recombination-radiation",
        "concept",
        "复合辐射",
        "recombination radiation",
        "",
        "active",
        "Radiation from free-bound electron transitions",
    ),
    (
        "charge-exchange-loss",
        "concept",
        "电荷交换损失",
        "charge-exchange loss",
        "",
        "active",
        "Energy loss from fast ion charge exchange with neutrals",
    ),
    (
        "radiation-barrier",
        "concept",
        "辐射垒",
        "radiation barrier",
        "",
        "active",
        "Edge radiation zone forming energy shielding layer",
    ),
    (
        "radiation-collapse",
        "concept",
        "辐射坍塌",
        "radiation collapse",
        "",
        "active",
        "Plasma temperature collapse from impurity radiation",
    ),
    (
        "z-effective",
        "metric",
        "有效电荷数",
        "effective charge number",
        "",
        "active",
        "Plasma effective nuclear charge Z_eff",
    ),
    (
        "doppler-broadening",
        "concept",
        "多普勒展宽",
        "Doppler broadening",
        "",
        "active",
        "Spectral line broadening from thermal motion",
    ),
    (
        "stark-broadening",
        "concept",
        "斯塔克展宽",
        "Stark broadening",
        "",
        "active",
        "Spectral line broadening from electric fields",
    ),
    (
        "continuum-radiation",
        "concept",
        "连续辐射",
        "continuum radiation",
        "",
        "active",
        "Bremsstrahlung plus recombination continuum spectrum",
    ),
    (
        "impurity-spectroscopy",
        "diagnostic",
        "杂质光谱",
        "impurity spectroscopy",
        "",
        "active",
        "Spectroscopic diagnostics of impurity content and transport",
    ),
    # Batch 38: Plasma Turbulence & Nonlinear Physics
    ("# ==== Batch 38: Plasma Turbulence & Nonlinear Physics ====",),
    (
        "turbulence-saturation",
        "concept",
        "湍流饱和",
        "turbulence saturation",
        "",
        "active",
        "Nonlinear saturation mechanism of micro-instabilities",
    ),
    (
        "turbulence-spreading",
        "concept",
        "湍流扩展",
        "turbulence spreading",
        "",
        "active",
        "Spatial diffusion of turbulence from unstable to stable regions",
    ),
    (
        "avalanche-transport",
        "concept",
        "雪崩输运",
        "avalanche transport",
        "",
        "active",
        "Cascade-triggered large-scale transient transport events",
    ),
    (
        "staircase-transport",
        "concept",
        "阶梯输运",
        "staircase transport",
        "",
        "active",
        "Self-organized staircase-like transport barrier structures in profiles",
    ),
    (
        "predator-prey-oscillation",
        "concept",
        "捕食-被捕食振荡",
        "predator-prey oscillation",
        "",
        "active",
        "Nonlinear oscillation between turbulence and zonal flows",
    ),
    (
        "nonlinear-coupling",
        "concept",
        "非线性耦合",
        "nonlinear coupling",
        "",
        "active",
        "Nonlinear interaction between different modes or scales",
    ),
    (
        "turbulence-suppression",
        "concept",
        "湍流抑制",
        "turbulence suppression",
        "",
        "active",
        "Turbulence suppression by E×B shear and other mechanisms",
    ),
    (
        "critical-balance",
        "concept",
        "临界平衡",
        "critical balance",
        "",
        "active",
        "Nonlinear balance state between parallel and perpendicular time scales",
    ),
    (
        "spectral-transfer",
        "concept",
        "能谱级联",
        "spectral transfer",
        "",
        "active",
        "Turbulent energy cascade transfer in wavenumber space",
    ),
    (
        "subcritical-turbulence",
        "concept",
        "亚临界湍流",
        "subcritical turbulence",
        "",
        "active",
        "Finite-amplitude turbulence maintained below linear critical gradient",
    ),
    # Batch 39: Radiation Damage & Materials Science
    ("# ==== Batch 39: Radiation Damage & Materials Science ====",),
    (
        "cascade-damage",
        "concept",
        "级联损伤",
        "cascade damage",
        "",
        "active",
        "Atomic displacement defect cascade from energetic particle impact",
    ),
    (
        "frenkel-pair",
        "concept",
        "Frenkel缺陷对",
        "Frenkel pair",
        "",
        "active",
        "Irradiation-produced interstitial atom and vacancy pair",
    ),
    (
        "interstitial-atom",
        "concept",
        "间隙原子",
        "interstitial atom",
        "",
        "active",
        "Atom displaced to interstitial lattice position",
    ),
    (
        "vacancy",
        "concept",
        "空位",
        "vacancy",
        "",
        "active",
        "Missing atom site in crystal lattice",
    ),
    (
        "recrystallization",
        "concept",
        "再结晶",
        "recrystallization",
        "",
        "active",
        "New grain nucleation and growth during high-temperature annealing",
    ),
    (
        "helium-bubble",
        "concept",
        "氦泡",
        "helium bubble",
        "",
        "active",
        "Helium accumulation forming bubbles in material from (n,alpha) reactions",
    ),
    (
        "tungsten-fuzz",
        "concept",
        "钨绒毛",
        "tungsten fuzz",
        "",
        "active",
        "Nano-fuzz surface structure on tungsten from low-energy He irradiation",
    ),
    (
        "radiation-hardening",
        "concept",
        "辐照硬化",
        "radiation hardening",
        "",
        "active",
        "Material hardening and embrittlement from neutron irradiation",
    ),
    (
        "radiation-induced-segregation",
        "concept",
        "辐照偏析",
        "radiation-induced segregation",
        "RIS",
        "active",
        "Irradiation-driven solute segregation in alloys",
    ),
    (
        "post-irradiation-examination",
        "method",
        "辐照后检验",
        "post-irradiation examination",
        "PIE",
        "active",
        "Hot cell examination and analysis of irradiated materials",
    ),
    # Batch 40: PFC Engineering & Thermal Management
    ("# ==== Batch 40: PFC Engineering & Thermal Management ====",),
    (
        "armor-tile",
        "system",
        "装甲瓦",
        "armor tile",
        "",
        "active",
        "Plasma-facing protective tile on divertor or first wall",
    ),
    (
        "heat-sink",
        "system",
        "热沉",
        "heat sink",
        "",
        "active",
        "Heat dissipation substrate in PFC (e.g. CuCrZr)",
    ),
    (
        "cooling-channel",
        "system",
        "冷却通道",
        "cooling channel",
        "",
        "active",
        "Internal coolant flow channel in PFC",
    ),
    (
        "hypervapotron",
        "system",
        "超蒸发管",
        "hypervapotron",
        "",
        "active",
        "Slotted enhanced boiling heat transfer structure for high heat flux cooling",
    ),
    (
        "swirl-tube",
        "system",
        "旋流管",
        "swirl tube",
        "",
        "active",
        "Cooling tube with internal helical swirl promoter",
    ),
    (
        "high-heat-flux-testing",
        "method",
        "高热流测试",
        "high heat flux testing",
        "HHF",
        "active",
        "High power thermal load qualification testing of PFC components",
    ),
    (
        "plasma-spray-coating",
        "method",
        "等离子喷涂",
        "plasma spray coating",
        "",
        "active",
        "Plasma spray deposition of tungsten or other PFM coatings",
    ),
    (
        "braze-joint",
        "system",
        "钎焊接头",
        "braze joint",
        "",
        "active",
        "Brazed W-CuCrZr joint in PFC",
    ),
    (
        "thermal-barrier-coating",
        "system",
        "热障涂层",
        "thermal barrier coating",
        "TBC",
        "active",
        "Thermal protection barrier coating",
    ),
    (
        "actively-cooled-component",
        "system",
        "主动冷却部件",
        "actively cooled component",
        "",
        "active",
        "PFC with integrated cooling circuit",
    ),
    # Batch 41: Advanced Divertor & Liquid Metals
    ("# ==== Batch 41: Advanced Divertor & Liquid Metals ====",),
    (
        "liquid-metal-divertor",
        "system",
        "液态金属偏滤器",
        "liquid metal divertor",
        "",
        "active",
        "Divertor using flowing liquid metal as exhaust surface",
    ),
    (
        "vapor-shielding",
        "concept",
        "蒸汽屏蔽",
        "vapor shielding",
        "",
        "active",
        "Self-protecting radiation shield from liquid metal evaporation",
    ),
    (
        "detachment-control",
        "method",
        "脱靶控制",
        "detachment control",
        "",
        "active",
        "Active control to maintain divertor detachment state",
    ),
    (
        "closed-divertor",
        "system",
        "封闭偏滤器",
        "closed divertor",
        "",
        "active",
        "Structurally closed divertor for enhanced neutral gas pressure",
    ),
    (
        "divertor-pumping",
        "system",
        "偏滤器抽气",
        "divertor pumping",
        "",
        "active",
        "Particle exhaust and He ash removal from divertor region",
    ),
    (
        "neutral-pressure",
        "metric",
        "中性气压",
        "neutral pressure",
        "",
        "active",
        "Neutral particle gas pressure in the divertor region",
    ),
    (
        "advanced-divertor-concept",
        "concept",
        "先进偏滤器概念",
        "advanced divertor concept",
        "",
        "active",
        "Umbrella term for super-X, snowflake, long-leg etc. configurations",
    ),
    (
        "divertor-baffle",
        "system",
        "偏滤器挡板",
        "divertor baffle",
        "",
        "active",
        "Neutral particle baffle at divertor entrance",
    ),
    (
        "divertor-dome",
        "system",
        "偏滤器穹顶",
        "divertor dome",
        "",
        "active",
        "Central dome structure in ITER-type divertor",
    ),
    (
        "lithium-wall",
        "system",
        "锂壁",
        "lithium wall",
        "",
        "active",
        "Liquid lithium covered plasma-facing wall surface",
    ),
    # Batch 42: Collisional Transport & Neoclassical Physics
    ("# ==== Batch 42: Collisional Transport & Neoclassical Physics ====",),
    (
        "banana-regime",
        "concept",
        "香蕉区",
        "banana regime",
        "",
        "active",
        "Low collisionality neoclassical transport regime (nu* << 1)",
    ),
    (
        "plateau-regime",
        "concept",
        "坪区",
        "plateau regime",
        "",
        "active",
        "Intermediate collisionality neoclassical transport regime",
    ),
    (
        "pfirsch-schlueter-regime",
        "concept",
        "Pfirsch-Schlüter区",
        "Pfirsch-Schlüter regime",
        "",
        "active",
        "High collisionality neoclassical transport regime",
    ),
    (
        "collisionality",
        "metric",
        "碰撞率",
        "collisionality",
        "",
        "active",
        "Normalized collision frequency nu*",
    ),
    (
        "thermal-force",
        "concept",
        "热力",
        "thermal force",
        "",
        "active",
        "Friction force component from temperature gradient",
    ),
    (
        "friction-force",
        "concept",
        "摩擦力",
        "friction force",
        "",
        "active",
        "Collisional friction force between different particle species",
    ),
    (
        "bootstrap-generation",
        "concept",
        "自举电流产生",
        "bootstrap generation",
        "",
        "active",
        "Current driven by trapped-passing particle asymmetry",
    ),
    (
        "poloidal-asymmetry",
        "concept",
        "极向不对称性",
        "poloidal asymmetry",
        "",
        "active",
        "Poloidal non-uniform distribution of high-Z impurity density",
    ),
    (
        "neoclassical-impurity-transport",
        "concept",
        "新经典杂质输运",
        "neoclassical impurity transport",
        "",
        "active",
        "Collision-driven inward/outward impurity transport",
    ),
    (
        "collisional-damping",
        "concept",
        "碰撞阻尼",
        "collisional damping",
        "",
        "active",
        "Wave or oscillation energy dissipation through collisions",
    ),
    # Batch 43: Remote Handling & Maintenance Engineering
    ("# ==== Batch 43: Remote Handling & Maintenance Engineering ====",),
    (
        "articulated-boom",
        "system",
        "铰接臂",
        "articulated boom",
        "",
        "active",
        "Multi-joint remote handling manipulator arm",
    ),
    (
        "cask-system",
        "system",
        "转运容器",
        "cask system",
        "",
        "active",
        "Shielded transfer cask for radioactive component transport",
    ),
    (
        "pipe-cutting",
        "method",
        "管道切割",
        "pipe cutting",
        "",
        "active",
        "Precision pipe cutting under remote handling",
    ),
    (
        "in-bore-welding",
        "method",
        "孔内焊接",
        "in-bore welding",
        "",
        "active",
        "In-bore pipe welding under remote handling",
    ),
    (
        "remote-inspection",
        "method",
        "远程检测",
        "remote inspection",
        "",
        "active",
        "Remote visual and ultrasonic inspection of in-vessel components",
    ),
    (
        "dose-rate-survey",
        "method",
        "剂量率巡测",
        "dose rate survey",
        "",
        "active",
        "Radiation field dose rate measurement for maintenance",
    ),
    (
        "maintenance-port",
        "system",
        "维护窗口",
        "maintenance port",
        "",
        "active",
        "Vacuum vessel access port for remote handling maintenance",
    ),
    (
        "component-lifetime",
        "metric",
        "部件寿命",
        "component lifetime",
        "",
        "active",
        "Design service lifetime of replaceable PFC/blanket modules",
    ),
    (
        "scheduled-maintenance",
        "method",
        "计划维护",
        "scheduled maintenance",
        "",
        "active",
        "Periodic planned component replacement or overhaul",
    ),
    (
        "divertor-replacement",
        "method",
        "偏滤器更换",
        "divertor replacement",
        "",
        "active",
        "Remote handling replacement of divertor cassettes",
    ),
    # Batch 44: AI & Digital Technologies
    ("# ==== Batch 44: AI & Digital Technologies ====",),
    (
        "digital-twin",
        "concept",
        "数字孪生",
        "digital twin",
        "",
        "active",
        "Real-time digital simulation mirror of fusion device",
    ),
    (
        "surrogate-model",
        "method",
        "代理模型",
        "surrogate model",
        "",
        "active",
        "Fast approximate model replacing high-fidelity physics simulation",
    ),
    (
        "ml-disruption-prediction",
        "method",
        "机器学习破裂预测",
        "ML disruption prediction",
        "",
        "active",
        "Machine learning based plasma disruption warning",
    ),
    (
        "neural-network-transport",
        "method",
        "神经网络输运模型",
        "neural network transport model",
        "",
        "active",
        "Neural network surrogate for transport prediction replacing TGLF etc.",
    ),
    (
        "bayesian-inference",
        "method",
        "贝叶斯推断",
        "Bayesian inference",
        "",
        "active",
        "Bayesian method for plasma parameter inversion",
    ),
    (
        "data-driven-control",
        "method",
        "数据驱动控制",
        "data-driven control",
        "",
        "active",
        "Control strategy based on data rather than physics models",
    ),
    (
        "synthetic-diagnostics",
        "method",
        "合成诊断",
        "synthetic diagnostics",
        "",
        "active",
        "Virtual diagnostic signal synthesis from simulation results",
    ),
    (
        "integrated-modeling",
        "method",
        "集成建模",
        "integrated modeling",
        "",
        "active",
        "Multi-physics coupled whole-device simulation",
    ),
    (
        "workflow-automation",
        "method",
        "工作流自动化",
        "workflow automation",
        "",
        "active",
        "Automated orchestration of simulation and analysis pipelines",
    ),
    (
        "uncertainty-quantification",
        "method",
        "不确定性量化",
        "uncertainty quantification",
        "UQ",
        "active",
        "Systematic assessment of model prediction uncertainties",
    ),
]

ALIASES = [
    # Batch 36: ICF Physics & Implosion
    ("# ==== Batch 36: ICF Physics & Implosion ====",),
    ("convergence ratio", "convergence-ratio", "en", "preferred", ""),
    ("收敛比", "convergence-ratio", "zh", "preferred", ""),
    ("areal density", "areal-density", "en", "preferred", ""),
    ("面密度", "areal-density", "zh", "preferred", ""),
    ("rho-R", "areal-density", "en", "alias", ""),
    (
        "Richtmyer-Meshkov instability",
        "richtmyer-meshkov-instability",
        "en",
        "preferred",
        "",
    ),
    ("RMI", "richtmyer-meshkov-instability", "abbr", "preferred", ""),
    (
        "Richtmyer-Meshkov不稳定性",
        "richtmyer-meshkov-instability",
        "zh",
        "preferred",
        "",
    ),
    ("ablation front", "ablation-front", "en", "preferred", ""),
    ("烧蚀前沿", "ablation-front", "zh", "preferred", ""),
    ("implosion velocity", "implosion-velocity", "en", "preferred", ""),
    ("内爆速度", "implosion-velocity", "zh", "preferred", ""),
    ("hot-spot ignition", "hot-spot-ignition", "en", "preferred", ""),
    ("中心热斑点火", "hot-spot-ignition", "zh", "preferred", ""),
    ("central hot spot ignition", "hot-spot-ignition", "en", "alias", ""),
    ("capsule implosion", "capsule-implosion", "en", "preferred", ""),
    ("靶丸内爆", "capsule-implosion", "zh", "preferred", ""),
    ("mix instability", "mix-instability", "en", "preferred", ""),
    ("混合不稳定性", "mix-instability", "zh", "preferred", ""),
    ("laser energy balance", "laser-energy-balance", "en", "preferred", ""),
    ("激光能量平衡", "laser-energy-balance", "zh", "preferred", ""),
    ("gain curve", "gain-curve", "en", "preferred", ""),
    ("增益曲线", "gain-curve", "zh", "preferred", ""),
    # Batch 37: Plasma Radiation & Spectroscopy
    ("# ==== Batch 37: Plasma Radiation & Spectroscopy ====",),
    ("line radiation", "line-radiation", "en", "preferred", ""),
    ("线辐射", "line-radiation", "zh", "preferred", ""),
    ("recombination radiation", "recombination-radiation", "en", "preferred", ""),
    ("复合辐射", "recombination-radiation", "zh", "preferred", ""),
    ("charge-exchange loss", "charge-exchange-loss", "en", "preferred", ""),
    ("电荷交换损失", "charge-exchange-loss", "zh", "preferred", ""),
    ("CX loss", "charge-exchange-loss", "en", "alias", ""),
    ("radiation barrier", "radiation-barrier", "en", "preferred", ""),
    ("辐射垒", "radiation-barrier", "zh", "preferred", ""),
    ("radiation collapse", "radiation-collapse", "en", "preferred", ""),
    ("辐射坍塌", "radiation-collapse", "zh", "preferred", ""),
    ("effective charge number", "z-effective", "en", "preferred", ""),
    ("有效电荷数", "z-effective", "zh", "preferred", ""),
    ("Z_eff", "z-effective", "en", "alias", ""),
    ("Zeff", "z-effective", "en", "alias", ""),
    ("Doppler broadening", "doppler-broadening", "en", "preferred", ""),
    ("多普勒展宽", "doppler-broadening", "zh", "preferred", ""),
    ("Stark broadening", "stark-broadening", "en", "preferred", ""),
    ("斯塔克展宽", "stark-broadening", "zh", "preferred", ""),
    ("continuum radiation", "continuum-radiation", "en", "preferred", ""),
    ("连续辐射", "continuum-radiation", "zh", "preferred", ""),
    ("impurity spectroscopy", "impurity-spectroscopy", "en", "preferred", ""),
    ("杂质光谱", "impurity-spectroscopy", "zh", "preferred", ""),
    # Batch 38: Plasma Turbulence & Nonlinear Physics
    ("# ==== Batch 38: Plasma Turbulence & Nonlinear Physics ====",),
    ("turbulence saturation", "turbulence-saturation", "en", "preferred", ""),
    ("湍流饱和", "turbulence-saturation", "zh", "preferred", ""),
    ("turbulence spreading", "turbulence-spreading", "en", "preferred", ""),
    ("湍流扩展", "turbulence-spreading", "zh", "preferred", ""),
    ("avalanche transport", "avalanche-transport", "en", "preferred", ""),
    ("雪崩输运", "avalanche-transport", "zh", "preferred", ""),
    ("staircase transport", "staircase-transport", "en", "preferred", ""),
    ("阶梯输运", "staircase-transport", "zh", "preferred", ""),
    ("predator-prey oscillation", "predator-prey-oscillation", "en", "preferred", ""),
    ("捕食-被捕食振荡", "predator-prey-oscillation", "zh", "preferred", ""),
    ("nonlinear coupling", "nonlinear-coupling", "en", "preferred", ""),
    ("非线性耦合", "nonlinear-coupling", "zh", "preferred", ""),
    ("turbulence suppression", "turbulence-suppression", "en", "preferred", ""),
    ("湍流抑制", "turbulence-suppression", "zh", "preferred", ""),
    ("critical balance", "critical-balance", "en", "preferred", ""),
    ("临界平衡", "critical-balance", "zh", "preferred", ""),
    ("spectral transfer", "spectral-transfer", "en", "preferred", ""),
    ("能谱级联", "spectral-transfer", "zh", "preferred", ""),
    ("subcritical turbulence", "subcritical-turbulence", "en", "preferred", ""),
    ("亚临界湍流", "subcritical-turbulence", "zh", "preferred", ""),
    # Batch 39: Radiation Damage & Materials Science
    ("# ==== Batch 39: Radiation Damage & Materials Science ====",),
    ("cascade damage", "cascade-damage", "en", "preferred", ""),
    ("级联损伤", "cascade-damage", "zh", "preferred", ""),
    ("displacement cascade", "cascade-damage", "en", "alias", ""),
    ("Frenkel pair", "frenkel-pair", "en", "preferred", ""),
    ("Frenkel缺陷对", "frenkel-pair", "zh", "preferred", ""),
    ("interstitial atom", "interstitial-atom", "en", "preferred", ""),
    ("间隙原子", "interstitial-atom", "zh", "preferred", ""),
    ("vacancy", "vacancy", "en", "preferred", ""),
    ("空位", "vacancy", "zh", "preferred", ""),
    ("recrystallization", "recrystallization", "en", "preferred", ""),
    ("再结晶", "recrystallization", "zh", "preferred", ""),
    ("helium bubble", "helium-bubble", "en", "preferred", ""),
    ("氦泡", "helium-bubble", "zh", "preferred", ""),
    ("He bubble", "helium-bubble", "en", "alias", ""),
    ("tungsten fuzz", "tungsten-fuzz", "en", "preferred", ""),
    ("钨绒毛", "tungsten-fuzz", "zh", "preferred", ""),
    ("W fuzz", "tungsten-fuzz", "en", "alias", ""),
    ("radiation hardening", "radiation-hardening", "en", "preferred", ""),
    ("辐照硬化", "radiation-hardening", "zh", "preferred", ""),
    (
        "radiation-induced segregation",
        "radiation-induced-segregation",
        "en",
        "preferred",
        "",
    ),
    ("RIS", "radiation-induced-segregation", "abbr", "preferred", ""),
    ("辐照偏析", "radiation-induced-segregation", "zh", "preferred", ""),
    (
        "post-irradiation examination",
        "post-irradiation-examination",
        "en",
        "preferred",
        "",
    ),
    ("PIE", "post-irradiation-examination", "abbr", "preferred", ""),
    ("辐照后检验", "post-irradiation-examination", "zh", "preferred", ""),
    # Batch 40: PFC Engineering & Thermal Management
    ("# ==== Batch 40: PFC Engineering & Thermal Management ====",),
    ("armor tile", "armor-tile", "en", "preferred", ""),
    ("装甲瓦", "armor-tile", "zh", "preferred", ""),
    ("heat sink", "heat-sink", "en", "preferred", ""),
    ("热沉", "heat-sink", "zh", "preferred", ""),
    ("cooling channel", "cooling-channel", "en", "preferred", ""),
    ("冷却通道", "cooling-channel", "zh", "preferred", ""),
    ("hypervapotron", "hypervapotron", "en", "preferred", ""),
    ("超蒸发管", "hypervapotron", "zh", "preferred", ""),
    ("swirl tube", "swirl-tube", "en", "preferred", ""),
    ("旋流管", "swirl-tube", "zh", "preferred", ""),
    ("high heat flux testing", "high-heat-flux-testing", "en", "preferred", ""),
    ("HHF", "high-heat-flux-testing", "abbr", "alias", ""),
    ("高热流测试", "high-heat-flux-testing", "zh", "preferred", ""),
    ("plasma spray coating", "plasma-spray-coating", "en", "preferred", ""),
    ("等离子喷涂", "plasma-spray-coating", "zh", "preferred", ""),
    ("braze joint", "braze-joint", "en", "preferred", ""),
    ("钎焊接头", "braze-joint", "zh", "preferred", ""),
    ("thermal barrier coating", "thermal-barrier-coating", "en", "preferred", ""),
    ("TBC", "thermal-barrier-coating", "abbr", "preferred", ""),
    ("热障涂层", "thermal-barrier-coating", "zh", "preferred", ""),
    ("actively cooled component", "actively-cooled-component", "en", "preferred", ""),
    ("主动冷却部件", "actively-cooled-component", "zh", "preferred", ""),
    # Batch 41: Advanced Divertor & Liquid Metals
    ("# ==== Batch 41: Advanced Divertor & Liquid Metals ====",),
    ("liquid metal divertor", "liquid-metal-divertor", "en", "preferred", ""),
    ("液态金属偏滤器", "liquid-metal-divertor", "zh", "preferred", ""),
    ("vapor shielding", "vapor-shielding", "en", "preferred", ""),
    ("蒸汽屏蔽", "vapor-shielding", "zh", "preferred", ""),
    ("detachment control", "detachment-control", "en", "preferred", ""),
    ("脱靶控制", "detachment-control", "zh", "preferred", ""),
    ("closed divertor", "closed-divertor", "en", "preferred", ""),
    ("封闭偏滤器", "closed-divertor", "zh", "preferred", ""),
    ("divertor pumping", "divertor-pumping", "en", "preferred", ""),
    ("偏滤器抽气", "divertor-pumping", "zh", "preferred", ""),
    ("neutral pressure", "neutral-pressure", "en", "preferred", ""),
    ("中性气压", "neutral-pressure", "zh", "preferred", ""),
    ("advanced divertor concept", "advanced-divertor-concept", "en", "preferred", ""),
    ("先进偏滤器概念", "advanced-divertor-concept", "zh", "preferred", ""),
    ("divertor baffle", "divertor-baffle", "en", "preferred", ""),
    ("偏滤器挡板", "divertor-baffle", "zh", "preferred", ""),
    ("divertor dome", "divertor-dome", "en", "preferred", ""),
    ("偏滤器穹顶", "divertor-dome", "zh", "preferred", ""),
    ("lithium wall", "lithium-wall", "en", "preferred", ""),
    ("锂壁", "lithium-wall", "zh", "preferred", ""),
    # Batch 42: Collisional Transport & Neoclassical Physics
    ("# ==== Batch 42: Collisional Transport & Neoclassical Physics ====",),
    ("banana regime", "banana-regime", "en", "preferred", ""),
    ("香蕉区", "banana-regime", "zh", "preferred", ""),
    ("plateau regime", "plateau-regime", "en", "preferred", ""),
    ("坪区", "plateau-regime", "zh", "preferred", ""),
    ("Pfirsch-Schlüter regime", "pfirsch-schlueter-regime", "en", "preferred", ""),
    ("Pfirsch-Schlüter区", "pfirsch-schlueter-regime", "zh", "preferred", ""),
    ("PS regime", "pfirsch-schlueter-regime", "en", "alias", ""),
    ("collisionality", "collisionality", "en", "preferred", ""),
    ("碰撞率", "collisionality", "zh", "preferred", ""),
    ("nu-star", "collisionality", "en", "alias", ""),
    ("thermal force", "thermal-force", "en", "preferred", ""),
    ("热力", "thermal-force", "zh", "preferred", ""),
    ("friction force", "friction-force", "en", "preferred", ""),
    ("摩擦力", "friction-force", "zh", "preferred", ""),
    ("bootstrap generation", "bootstrap-generation", "en", "preferred", ""),
    ("自举电流产生", "bootstrap-generation", "zh", "preferred", ""),
    ("poloidal asymmetry", "poloidal-asymmetry", "en", "preferred", ""),
    ("极向不对称性", "poloidal-asymmetry", "zh", "preferred", ""),
    (
        "neoclassical impurity transport",
        "neoclassical-impurity-transport",
        "en",
        "preferred",
        "",
    ),
    ("新经典杂质输运", "neoclassical-impurity-transport", "zh", "preferred", ""),
    ("collisional damping", "collisional-damping", "en", "preferred", ""),
    ("碰撞阻尼", "collisional-damping", "zh", "preferred", ""),
    # Batch 43: Remote Handling & Maintenance Engineering
    ("# ==== Batch 43: Remote Handling & Maintenance Engineering ====",),
    ("articulated boom", "articulated-boom", "en", "preferred", ""),
    ("铰接臂", "articulated-boom", "zh", "preferred", ""),
    ("cask system", "cask-system", "en", "preferred", ""),
    ("转运容器", "cask-system", "zh", "preferred", ""),
    ("transfer cask", "cask-system", "en", "alias", ""),
    ("pipe cutting", "pipe-cutting", "en", "preferred", ""),
    ("管道切割", "pipe-cutting", "zh", "preferred", ""),
    ("in-bore welding", "in-bore-welding", "en", "preferred", ""),
    ("孔内焊接", "in-bore-welding", "zh", "preferred", ""),
    ("remote inspection", "remote-inspection", "en", "preferred", ""),
    ("远程检测", "remote-inspection", "zh", "preferred", ""),
    ("dose rate survey", "dose-rate-survey", "en", "preferred", ""),
    ("剂量率巡测", "dose-rate-survey", "zh", "preferred", ""),
    ("maintenance port", "maintenance-port", "en", "preferred", ""),
    ("维护窗口", "maintenance-port", "zh", "preferred", ""),
    ("component lifetime", "component-lifetime", "en", "preferred", ""),
    ("部件寿命", "component-lifetime", "zh", "preferred", ""),
    ("scheduled maintenance", "scheduled-maintenance", "en", "preferred", ""),
    ("计划维护", "scheduled-maintenance", "zh", "preferred", ""),
    ("divertor replacement", "divertor-replacement", "en", "preferred", ""),
    ("偏滤器更换", "divertor-replacement", "zh", "preferred", ""),
    # Batch 44: AI & Digital Technologies
    ("# ==== Batch 44: AI & Digital Technologies ====",),
    ("digital twin", "digital-twin", "en", "preferred", ""),
    ("数字孪生", "digital-twin", "zh", "preferred", ""),
    ("surrogate model", "surrogate-model", "en", "preferred", ""),
    ("代理模型", "surrogate-model", "zh", "preferred", ""),
    ("ML disruption prediction", "ml-disruption-prediction", "en", "preferred", ""),
    ("机器学习破裂预测", "ml-disruption-prediction", "zh", "preferred", ""),
    (
        "neural network transport model",
        "neural-network-transport",
        "en",
        "preferred",
        "",
    ),
    ("神经网络输运模型", "neural-network-transport", "zh", "preferred", ""),
    ("Bayesian inference", "bayesian-inference", "en", "preferred", ""),
    ("贝叶斯推断", "bayesian-inference", "zh", "preferred", ""),
    ("data-driven control", "data-driven-control", "en", "preferred", ""),
    ("数据驱动控制", "data-driven-control", "zh", "preferred", ""),
    ("synthetic diagnostics", "synthetic-diagnostics", "en", "preferred", ""),
    ("合成诊断", "synthetic-diagnostics", "zh", "preferred", ""),
    ("integrated modeling", "integrated-modeling", "en", "preferred", ""),
    ("集成建模", "integrated-modeling", "zh", "preferred", ""),
    ("integrated modelling", "integrated-modeling", "en", "alias", ""),
    ("workflow automation", "workflow-automation", "en", "preferred", ""),
    ("工作流自动化", "workflow-automation", "zh", "preferred", ""),
    ("uncertainty quantification", "uncertainty-quantification", "en", "preferred", ""),
    ("UQ", "uncertainty-quantification", "abbr", "preferred", ""),
    ("不确定性量化", "uncertainty-quantification", "zh", "preferred", ""),
]

EVIDENCE = [
    (
        "convergence-ratio",
        "internal:expansion:batch-36",
        "Implosion radius ratio",
        "copilot",
        "2026-03-19",
    ),
    (
        "areal-density",
        "internal:expansion:batch-36",
        "Compressed fuel rho-R",
        "copilot",
        "2026-03-19",
    ),
    (
        "richtmyer-meshkov-instability",
        "internal:expansion:batch-36",
        "Shock-interface instability",
        "copilot",
        "2026-03-19",
    ),
    (
        "ablation-front",
        "internal:expansion:batch-36",
        "Ablating shell interface",
        "copilot",
        "2026-03-19",
    ),
    (
        "implosion-velocity",
        "internal:expansion:batch-36",
        "Shell inward velocity",
        "copilot",
        "2026-03-19",
    ),
    (
        "hot-spot-ignition",
        "internal:expansion:batch-36",
        "Central hot spot ignition",
        "copilot",
        "2026-03-19",
    ),
    (
        "capsule-implosion",
        "internal:expansion:batch-36",
        "ICF capsule compression",
        "copilot",
        "2026-03-19",
    ),
    (
        "mix-instability",
        "internal:expansion:batch-36",
        "Shell-fuel material mixing",
        "copilot",
        "2026-03-19",
    ),
    (
        "laser-energy-balance",
        "internal:expansion:batch-36",
        "Laser energy partition",
        "copilot",
        "2026-03-19",
    ),
    (
        "gain-curve",
        "internal:expansion:batch-36",
        "ICF gain vs energy curve",
        "copilot",
        "2026-03-19",
    ),
    (
        "line-radiation",
        "internal:expansion:batch-37",
        "Bound-bound transition radiation",
        "copilot",
        "2026-03-19",
    ),
    (
        "recombination-radiation",
        "internal:expansion:batch-37",
        "Free-bound radiation",
        "copilot",
        "2026-03-19",
    ),
    (
        "charge-exchange-loss",
        "internal:expansion:batch-37",
        "CX energy loss",
        "copilot",
        "2026-03-19",
    ),
    (
        "radiation-barrier",
        "internal:expansion:batch-37",
        "Edge radiation shielding",
        "copilot",
        "2026-03-19",
    ),
    (
        "radiation-collapse",
        "internal:expansion:batch-37",
        "Impurity radiation collapse",
        "copilot",
        "2026-03-19",
    ),
    (
        "z-effective",
        "internal:expansion:batch-37",
        "Plasma effective charge",
        "copilot",
        "2026-03-19",
    ),
    (
        "doppler-broadening",
        "internal:expansion:batch-37",
        "Thermal line broadening",
        "copilot",
        "2026-03-19",
    ),
    (
        "stark-broadening",
        "internal:expansion:batch-37",
        "Electric field broadening",
        "copilot",
        "2026-03-19",
    ),
    (
        "continuum-radiation",
        "internal:expansion:batch-37",
        "Brems+recomb continuum",
        "copilot",
        "2026-03-19",
    ),
    (
        "impurity-spectroscopy",
        "internal:expansion:batch-37",
        "Spectroscopic impurity diag",
        "copilot",
        "2026-03-19",
    ),
    (
        "turbulence-saturation",
        "internal:expansion:batch-38",
        "Nonlinear saturation",
        "copilot",
        "2026-03-19",
    ),
    (
        "turbulence-spreading",
        "internal:expansion:batch-38",
        "Spatial turbulence diffusion",
        "copilot",
        "2026-03-19",
    ),
    (
        "avalanche-transport",
        "internal:expansion:batch-38",
        "Cascade transient transport",
        "copilot",
        "2026-03-19",
    ),
    (
        "staircase-transport",
        "internal:expansion:batch-38",
        "Self-organized barriers",
        "copilot",
        "2026-03-19",
    ),
    (
        "predator-prey-oscillation",
        "internal:expansion:batch-38",
        "Turbulence-zonal flow cycle",
        "copilot",
        "2026-03-19",
    ),
    (
        "nonlinear-coupling",
        "internal:expansion:batch-38",
        "Inter-mode coupling",
        "copilot",
        "2026-03-19",
    ),
    (
        "turbulence-suppression",
        "internal:expansion:batch-38",
        "ExB shear suppression",
        "copilot",
        "2026-03-19",
    ),
    (
        "critical-balance",
        "internal:expansion:batch-38",
        "Parallel-perp timescale balance",
        "copilot",
        "2026-03-19",
    ),
    (
        "spectral-transfer",
        "internal:expansion:batch-38",
        "Wavenumber cascade",
        "copilot",
        "2026-03-19",
    ),
    (
        "subcritical-turbulence",
        "internal:expansion:batch-38",
        "Below-threshold turbulence",
        "copilot",
        "2026-03-19",
    ),
    (
        "cascade-damage",
        "internal:expansion:batch-39",
        "Displacement cascade",
        "copilot",
        "2026-03-19",
    ),
    (
        "frenkel-pair",
        "internal:expansion:batch-39",
        "Interstitial-vacancy pair",
        "copilot",
        "2026-03-19",
    ),
    (
        "interstitial-atom",
        "internal:expansion:batch-39",
        "Displaced interstitial",
        "copilot",
        "2026-03-19",
    ),
    (
        "vacancy",
        "internal:expansion:batch-39",
        "Lattice vacancy defect",
        "copilot",
        "2026-03-19",
    ),
    (
        "recrystallization",
        "internal:expansion:batch-39",
        "High-temp grain regrowth",
        "copilot",
        "2026-03-19",
    ),
    (
        "helium-bubble",
        "internal:expansion:batch-39",
        "He accumulation bubble",
        "copilot",
        "2026-03-19",
    ),
    (
        "tungsten-fuzz",
        "internal:expansion:batch-39",
        "He-irradiated W nano-fuzz",
        "copilot",
        "2026-03-19",
    ),
    (
        "radiation-hardening",
        "internal:expansion:batch-39",
        "Neutron hardening",
        "copilot",
        "2026-03-19",
    ),
    (
        "radiation-induced-segregation",
        "internal:expansion:batch-39",
        "Irradiation solute segregation",
        "copilot",
        "2026-03-19",
    ),
    (
        "post-irradiation-examination",
        "internal:expansion:batch-39",
        "Hot cell PIE analysis",
        "copilot",
        "2026-03-19",
    ),
    (
        "armor-tile",
        "internal:expansion:batch-40",
        "PFC protective tile",
        "copilot",
        "2026-03-19",
    ),
    (
        "heat-sink",
        "internal:expansion:batch-40",
        "PFC heat dissipation",
        "copilot",
        "2026-03-19",
    ),
    (
        "cooling-channel",
        "internal:expansion:batch-40",
        "PFC coolant channel",
        "copilot",
        "2026-03-19",
    ),
    (
        "hypervapotron",
        "internal:expansion:batch-40",
        "Enhanced boiling structure",
        "copilot",
        "2026-03-19",
    ),
    (
        "swirl-tube",
        "internal:expansion:batch-40",
        "Helical swirl cooling",
        "copilot",
        "2026-03-19",
    ),
    (
        "high-heat-flux-testing",
        "internal:expansion:batch-40",
        "HHF component testing",
        "copilot",
        "2026-03-19",
    ),
    (
        "plasma-spray-coating",
        "internal:expansion:batch-40",
        "PFM spray deposition",
        "copilot",
        "2026-03-19",
    ),
    (
        "braze-joint",
        "internal:expansion:batch-40",
        "W-CuCrZr braze",
        "copilot",
        "2026-03-19",
    ),
    (
        "thermal-barrier-coating",
        "internal:expansion:batch-40",
        "TBC thermal protection",
        "copilot",
        "2026-03-19",
    ),
    (
        "actively-cooled-component",
        "internal:expansion:batch-40",
        "Cooled PFC",
        "copilot",
        "2026-03-19",
    ),
    (
        "liquid-metal-divertor",
        "internal:expansion:batch-41",
        "Liquid metal exhaust surface",
        "copilot",
        "2026-03-19",
    ),
    (
        "vapor-shielding",
        "internal:expansion:batch-41",
        "LM evaporation self-protection",
        "copilot",
        "2026-03-19",
    ),
    (
        "detachment-control",
        "internal:expansion:batch-41",
        "Divertor detachment control",
        "copilot",
        "2026-03-19",
    ),
    (
        "closed-divertor",
        "internal:expansion:batch-41",
        "Enclosed divertor structure",
        "copilot",
        "2026-03-19",
    ),
    (
        "divertor-pumping",
        "internal:expansion:batch-41",
        "He ash pumping",
        "copilot",
        "2026-03-19",
    ),
    (
        "neutral-pressure",
        "internal:expansion:batch-41",
        "Divertor neutral gas pressure",
        "copilot",
        "2026-03-19",
    ),
    (
        "advanced-divertor-concept",
        "internal:expansion:batch-41",
        "Advanced divertor umbrella",
        "copilot",
        "2026-03-19",
    ),
    (
        "divertor-baffle",
        "internal:expansion:batch-41",
        "Neutral baffle at entry",
        "copilot",
        "2026-03-19",
    ),
    (
        "divertor-dome",
        "internal:expansion:batch-41",
        "ITER dome structure",
        "copilot",
        "2026-03-19",
    ),
    (
        "lithium-wall",
        "internal:expansion:batch-41",
        "Li plasma-facing wall",
        "copilot",
        "2026-03-19",
    ),
    (
        "banana-regime",
        "internal:expansion:batch-42",
        "Low-collisionality regime",
        "copilot",
        "2026-03-19",
    ),
    (
        "plateau-regime",
        "internal:expansion:batch-42",
        "Intermediate collisionality",
        "copilot",
        "2026-03-19",
    ),
    (
        "pfirsch-schlueter-regime",
        "internal:expansion:batch-42",
        "High-collisionality regime",
        "copilot",
        "2026-03-19",
    ),
    (
        "collisionality",
        "internal:expansion:batch-42",
        "Normalized collision freq",
        "copilot",
        "2026-03-19",
    ),
    (
        "thermal-force",
        "internal:expansion:batch-42",
        "Temperature gradient force",
        "copilot",
        "2026-03-19",
    ),
    (
        "friction-force",
        "internal:expansion:batch-42",
        "Inter-species friction",
        "copilot",
        "2026-03-19",
    ),
    (
        "bootstrap-generation",
        "internal:expansion:batch-42",
        "Trapped-passing asymmetry",
        "copilot",
        "2026-03-19",
    ),
    (
        "poloidal-asymmetry",
        "internal:expansion:batch-42",
        "High-Z poloidal variation",
        "copilot",
        "2026-03-19",
    ),
    (
        "neoclassical-impurity-transport",
        "internal:expansion:batch-42",
        "Collision-driven impurity transport",
        "copilot",
        "2026-03-19",
    ),
    (
        "collisional-damping",
        "internal:expansion:batch-42",
        "Collision energy dissipation",
        "copilot",
        "2026-03-19",
    ),
    (
        "articulated-boom",
        "internal:expansion:batch-43",
        "Multi-joint manipulator arm",
        "copilot",
        "2026-03-19",
    ),
    (
        "cask-system",
        "internal:expansion:batch-43",
        "Shielded transfer device",
        "copilot",
        "2026-03-19",
    ),
    (
        "pipe-cutting",
        "internal:expansion:batch-43",
        "Remote pipe cutting",
        "copilot",
        "2026-03-19",
    ),
    (
        "in-bore-welding",
        "internal:expansion:batch-43",
        "Remote bore welding",
        "copilot",
        "2026-03-19",
    ),
    (
        "remote-inspection",
        "internal:expansion:batch-43",
        "In-vessel remote inspection",
        "copilot",
        "2026-03-19",
    ),
    (
        "dose-rate-survey",
        "internal:expansion:batch-43",
        "Radiation field measurement",
        "copilot",
        "2026-03-19",
    ),
    (
        "maintenance-port",
        "internal:expansion:batch-43",
        "VV maintenance access",
        "copilot",
        "2026-03-19",
    ),
    (
        "component-lifetime",
        "internal:expansion:batch-43",
        "Replaceable component life",
        "copilot",
        "2026-03-19",
    ),
    (
        "scheduled-maintenance",
        "internal:expansion:batch-43",
        "Periodic overhaul",
        "copilot",
        "2026-03-19",
    ),
    (
        "divertor-replacement",
        "internal:expansion:batch-43",
        "Remote cassette replacement",
        "copilot",
        "2026-03-19",
    ),
    (
        "digital-twin",
        "internal:expansion:batch-44",
        "Real-time device mirror",
        "copilot",
        "2026-03-19",
    ),
    (
        "surrogate-model",
        "internal:expansion:batch-44",
        "Fast approximate model",
        "copilot",
        "2026-03-19",
    ),
    (
        "ml-disruption-prediction",
        "internal:expansion:batch-44",
        "ML disruption warning",
        "copilot",
        "2026-03-19",
    ),
    (
        "neural-network-transport",
        "internal:expansion:batch-44",
        "NN transport surrogate",
        "copilot",
        "2026-03-19",
    ),
    (
        "bayesian-inference",
        "internal:expansion:batch-44",
        "Bayesian parameter inversion",
        "copilot",
        "2026-03-19",
    ),
    (
        "data-driven-control",
        "internal:expansion:batch-44",
        "Data-based control strategy",
        "copilot",
        "2026-03-19",
    ),
    (
        "synthetic-diagnostics",
        "internal:expansion:batch-44",
        "Virtual diagnostic signal",
        "copilot",
        "2026-03-19",
    ),
    (
        "integrated-modeling",
        "internal:expansion:batch-44",
        "Multi-physics simulation",
        "copilot",
        "2026-03-19",
    ),
    (
        "workflow-automation",
        "internal:expansion:batch-44",
        "Pipeline automation",
        "copilot",
        "2026-03-19",
    ),
    (
        "uncertainty-quantification",
        "internal:expansion:batch-44",
        "Prediction UQ",
        "copilot",
        "2026-03-19",
    ),
]


def write_tsv_rows(path, rows):
    with open(path, "a", encoding="utf-8") as f:
        for row in rows:
            if len(row) == 1:
                f.write(row[0] + "\n")
            else:
                f.write(T.join(row) + "\n")


if __name__ == "__main__":
    write_tsv_rows(REG / "concepts.tsv", CONCEPTS)
    n_c = sum(1 for r in CONCEPTS if len(r) > 1)
    print(f"Appended {n_c} concepts")

    write_tsv_rows(REG / "aliases.tsv", ALIASES)
    n_a = sum(1 for r in ALIASES if len(r) > 1)
    print(f"Appended {n_a} aliases")

    write_tsv_rows(REG / "evidence.tsv", EVIDENCE)
    print(f"Appended {len(EVIDENCE)} evidence rows")
