#!/usr/bin/env python3
"""Append Batch 27-35 terms to the registry with proper TSV formatting."""

import pathlib

REG = pathlib.Path("terms/registry")
T = "\t"

CONCEPTS = [
    # Batch 27: RF Heating & Current Drive Physics
    ("# ==== Batch 27: RF Heating & Current Drive Physics ====",),
    ("minority-heating", "concept", "少数粒子加热", "minority heating", "", "active", "ICRF minority ion resonance heating scheme"),
    ("harmonic-heating", "concept", "谐波加热", "harmonic heating", "", "active", "Heating at higher harmonics of the cyclotron frequency"),
    ("mode-conversion", "concept", "模式转换", "mode conversion", "", "active", "Wave mode conversion heating mechanism at ion-ion hybrid layer"),
    ("antenna-coupling", "concept", "天线耦合", "antenna coupling", "", "active", "RF wave coupling from antenna to plasma"),
    ("wave-absorption", "concept", "波吸收", "wave absorption", "", "active", "Plasma power absorption of RF waves"),
    ("n-parallel", "metric", "平行折射率", "parallel refractive index", "", "active", "Parallel wave vector component N_parallel controlling wave-plasma interaction"),
    ("multipactor", "concept", "二次电子倍增放电", "multipactor", "", "active", "Secondary electron multiplication discharge in RF components"),
    ("full-wave-simulation", "method", "全波模拟", "full-wave simulation", "", "active", "Full Maxwell equation wave propagation simulation"),
    ("antenna-loading", "metric", "天线负载", "antenna loading", "", "active", "Plasma coupling component of antenna impedance"),
    ("faraday-screen", "system", "法拉第屏", "Faraday screen", "", "active", "Electrostatic screen in front of ICRF antenna"),
    # Batch 28: Particle Orbit Physics
    ("# ==== Batch 28: Particle Orbit Physics ====",),
    ("passing-particle", "concept", "通行粒子", "passing particle", "", "active", "Untrapped particle traversing the full torus"),
    ("trapped-particle", "concept", "俘获粒子", "trapped particle", "", "active", "Banana-orbit particle reflected by magnetic mirror force"),
    ("bounce-frequency", "metric", "弹跳频率", "bounce frequency", "", "active", "Oscillation frequency of trapped particle in banana orbit"),
    ("precession-drift", "concept", "进动漂移", "toroidal precession drift", "", "active", "Toroidal precession of trapped particles"),
    ("exb-drift", "concept", "E×B漂移", "E×B drift", "", "active", "Particle drift perpendicular to both E and B fields"),
    ("grad-b-drift", "concept", "∇B漂移", "grad-B drift", "", "active", "Particle drift due to magnetic field gradient"),
    ("curvature-drift", "concept", "曲率漂移", "curvature drift", "", "active", "Particle drift due to magnetic field line curvature"),
    ("diamagnetic-drift", "concept", "抗磁漂移", "diamagnetic drift", "", "active", "Fluid drift driven by pressure gradient"),
    ("orbit-loss", "concept", "轨道损失", "orbit loss", "", "active", "Fast ion loss due to large orbit width exceeding confinement"),
    ("prompt-loss", "concept", "瞬时损失", "prompt loss", "", "active", "Fast ion loss on first orbit after birth"),
    # Batch 29: Confinement Scaling & Performance Metrics
    ("# ==== Batch 29: Confinement Scaling & Performance Metrics ====",),
    ("confinement-scaling", "concept", "约束标度律", "confinement scaling law", "", "active", "Empirical scaling law for energy confinement time"),
    ("h-factor", "metric", "H因子", "H-factor", "", "active", "Confinement quality factor tau_E / tau_scaling"),
    ("troyon-limit", "metric", "Troyon极限", "Troyon limit", "", "active", "MHD stability limit on normalized beta_N"),
    ("greenwald-fraction", "metric", "Greenwald份额", "Greenwald fraction", "", "active", "Ratio of line-averaged density to Greenwald density"),
    ("power-degradation", "concept", "功率退化", "power degradation", "", "active", "Confinement degradation with increasing heating power"),
    ("isotope-effect", "concept", "同位素效应", "isotope effect", "", "active", "Confinement dependence on hydrogen isotope mass"),
    ("size-scaling", "concept", "尺寸标度", "size scaling", "", "active", "Confinement scaling with device size"),
    ("mhd-stability-limit", "metric", "MHD稳定极限", "MHD stability limit", "", "active", "MHD stability boundary of plasma operation"),
    ("density-limit", "metric", "密度极限", "density limit", "", "active", "Maximum sustainable plasma density boundary"),
    ("stored-energy", "metric", "等离子体储能", "stored energy", "", "active", "Total thermodynamic energy of confined plasma"),
    # Batch 30: Plasma Control & Actuators
    ("# ==== Batch 30: Plasma Control & Actuators ====",),
    ("vertical-stability", "concept", "垂直稳定性", "vertical stability", "", "active", "Axisymmetric stability of elongated plasma"),
    ("gap-control", "method", "间隙控制", "gap control", "", "active", "Feedback control of plasma-wall clearance"),
    ("kinetic-control", "method", "动理学控制", "kinetic control", "", "active", "Active control of plasma kinetic profiles"),
    ("burn-control", "method", "燃烧控制", "burn control", "", "active", "Active regulation of fusion burn conditions"),
    ("actuator", "concept", "执行器", "actuator", "", "active", "Physical action device for plasma control"),
    ("plasma-ramp-up", "concept", "等离子体升流", "plasma ramp-up", "", "active", "Initial plasma current ramp-up phase"),
    ("plasma-ramp-down", "concept", "等离子体降流", "plasma ramp-down", "", "active", "Plasma current termination ramp-down phase"),
    ("feedback-control", "method", "反馈控制", "feedback control", "", "active", "Closed-loop control based on real-time measurements"),
    ("model-predictive-control", "method", "模型预测控制", "model predictive control", "MPC", "active", "Model-based feedforward + feedback optimization control"),
    ("plasma-state-estimation", "method", "等离子体状态估计", "plasma state estimation", "", "active", "Reconstruction of full plasma state from limited diagnostics"),
    # Batch 31: Blanket Engineering Details
    ("# ==== Batch 31: Blanket Engineering Details ====",),
    ("beryllium-multiplier", "system", "铍中子倍增层", "beryllium multiplier", "", "active", "Neutron multiplication layer in solid blanket using beryllium"),
    ("breeding-zone", "system", "增殖区", "breeding zone", "", "active", "Blanket region containing tritium breeding material"),
    ("back-plate", "system", "背板", "back plate", "", "active", "Structural support plate behind the first wall"),
    ("coolant-manifold", "system", "冷却歧管", "coolant manifold", "", "active", "Blanket coolant distribution and collection manifold"),
    ("purge-gas", "concept", "吹扫气", "purge gas", "", "active", "Helium gas for extracting tritium from ceramic breeders"),
    ("thermal-fatigue", "concept", "热疲劳", "thermal fatigue", "", "active", "Material fatigue from cyclic thermal loading"),
    ("irradiation-creep", "concept", "辐照蠕变", "irradiation creep", "", "active", "Neutron irradiation enhanced creep deformation"),
    ("functional-material", "material", "功能材料", "functional material", "", "active", "Multiplier, breeder and coolant materials in blanket"),
    ("coolant-chemistry", "concept", "冷却剂化学", "coolant chemistry", "", "active", "Chemical control of blanket coolant"),
    ("thermo-mechanical-analysis", "method", "热机械分析", "thermo-mechanical analysis", "", "active", "Coupled thermal and mechanical stress analysis"),
    # Batch 32: Vacuum & Fueling Technology
    ("# ==== Batch 32: Vacuum & Fueling Technology ====",),
    ("vacuum-pumping", "system", "真空抽气", "vacuum pumping", "", "active", "Pumping system maintaining vacuum vessel base pressure"),
    ("base-pressure", "metric", "本底气压", "base pressure", "", "active", "Vacuum vessel background pressure before plasma operation"),
    ("outgassing", "concept", "出气", "outgassing", "", "active", "Release of adsorbed gases from vacuum vessel walls"),
    ("bakeout", "method", "真空烘烤", "bakeout", "", "active", "High-temperature degassing to reduce base pressure"),
    ("gas-injection-valve", "system", "进气阀", "gas injection valve", "", "active", "Fast electromagnetic valve for gas injection"),
    ("pellet-guide-tube", "system", "弹丸导管", "pellet guide tube", "", "active", "Curved tube guiding pellets from injector to plasma"),
    ("pellet-ablation", "concept", "弹丸烧蚀", "pellet ablation", "", "active", "Fuel pellet surface ablation in hot plasma"),
    ("cryogenic-pellet", "system", "低温弹丸", "cryogenic pellet", "", "active", "Frozen hydrogen isotope fuel pellet"),
    ("compact-toroid-injection", "method", "紧凑环注入", "compact toroid injection", "CTI", "active", "CT injection for deep fueling and current drive"),
    ("gas-balance", "concept", "气体平衡", "gas balance", "", "active", "Balance of gas injection, recycling and pumping in device"),
    # Batch 33: Nuclear Analysis Details
    ("# ==== Batch 33: Nuclear Analysis Details ====",),
    ("nuclear-data-library", "concept", "核数据库", "nuclear data library", "", "active", "Evaluated nuclear data file collection (parent concept of ENDF/JEFF etc.)"),
    ("contact-dose-rate", "metric", "接触剂量率", "contact dose rate", "", "active", "Dose rate at the surface of activated components"),
    ("clearance-index", "metric", "清洁解控指数", "clearance index", "", "active", "Unconditional clearance criterion for radioactive waste"),
    ("gas-production-rate", "metric", "气体产额", "gas production rate", "", "active", "He/H gas production from nuclear reactions in materials"),
    ("helium-production", "concept", "氦产生", "helium production", "", "active", "Helium generation via (n,alpha) reactions in structural materials"),
    ("neutron-flux", "metric", "中子通量", "neutron flux", "", "active", "Neutron flow intensity per unit area"),
    ("photon-dose", "metric", "光子剂量", "photon dose", "", "active", "Radiation dose from secondary photons"),
    ("deep-penetration", "concept", "深穿透", "deep penetration", "", "active", "Neutron streaming in thick shielding"),
    ("activation-foil", "system", "活化箔", "activation foil", "", "active", "Metal foil for neutron spectrum measurement"),
    ("nuclear-response-function", "concept", "核响应函数", "nuclear response function", "", "active", "Response kernel for nuclear heating, He production etc."),
    # Batch 34: Fusion Economics & Project Management
    ("# ==== Batch 34: Fusion Economics & Project Management ====",),
    ("first-of-a-kind", "concept", "首台堆", "first-of-a-kind", "FOAK", "active", "First-built cost baseline for fusion power plant"),
    ("nth-of-a-kind", "concept", "第N台堆", "nth-of-a-kind", "NOAK", "active", "Series-production steady-state cost baseline"),
    ("learning-rate", "metric", "学习率", "learning rate", "", "active", "Cost reduction fraction per doubling of production units"),
    ("supply-chain", "concept", "供应链", "supply chain", "", "active", "Manufacturing and raw material supply chain for fusion components"),
    ("component-qualification", "method", "部件鉴定", "component qualification", "", "active", "Qualification procedure for critical nuclear components"),
    ("prototype-reactor", "concept", "原型堆", "prototype reactor", "", "active", "Engineering validation prototype before DEMO"),
    ("integrated-commissioning", "method", "综合调试", "integrated commissioning", "", "active", "System-level joint commissioning of the device"),
    ("construction-schedule", "concept", "建造进度", "construction schedule", "", "active", "Construction timeline for large fusion devices"),
    ("regulatory-approval", "concept", "审批许可", "regulatory approval", "", "active", "Government approval for nuclear facility construction and operation"),
    ("decommissioning-cost", "metric", "退役费用", "decommissioning cost", "", "active", "Device decommissioning and radioactive cleanup cost"),
    # Batch 35: Confinement Modes & Transport Phenomena
    ("# ==== Batch 35: Confinement Modes & Transport Phenomena ====",),
    ("i-mode", "concept", "I模", "I-mode", "", "active", "Intermediate confinement regime with L-mode density and H-mode temperature"),
    ("super-h-mode", "concept", "超级H模", "super H-mode", "", "active", "High-performance H-mode with very wide/tall pedestal"),
    ("density-peaking", "concept", "密度峰化", "density peaking", "", "active", "Density profile peaking toward plasma center"),
    ("impurity-accumulation", "concept", "杂质积聚", "impurity accumulation", "", "active", "High-Z impurity accumulation in plasma core"),
    ("tungsten-accumulation", "concept", "钨积聚", "tungsten accumulation", "", "active", "Hazardous tungsten impurity enrichment in core"),
    ("rotation-reversal", "concept", "旋转反转", "rotation reversal", "", "active", "Spontaneous rotation direction reversal at density transition"),
    ("density-pump-out", "concept", "密度泵出", "density pump-out", "", "active", "Transient density drop during H-mode transition"),
    ("temperature-pedestal", "concept", "温度基座", "temperature pedestal", "", "active", "H-mode edge temperature pedestal structure"),
    ("pressure-pedestal", "concept", "压力基座", "pressure pedestal", "", "active", "H-mode edge pressure pedestal structure"),
    ("pedestal-width", "metric", "基座宽度", "pedestal width", "", "active", "Radial width of H-mode pedestal"),
]

ALIASES = [
    # Batch 27: RF Heating & Current Drive Physics
    ("# ==== Batch 27: RF Heating & Current Drive Physics ====",),
    ("minority heating", "minority-heating", "en", "preferred", ""),
    ("少数粒子加热", "minority-heating", "zh", "preferred", ""),
    ("minority ion heating", "minority-heating", "en", "alias", ""),
    ("harmonic heating", "harmonic-heating", "en", "preferred", ""),
    ("谐波加热", "harmonic-heating", "zh", "preferred", ""),
    ("second harmonic heating", "harmonic-heating", "en", "alias", ""),
    ("mode conversion", "mode-conversion", "en", "preferred", ""),
    ("模式转换", "mode-conversion", "zh", "preferred", ""),
    ("antenna coupling", "antenna-coupling", "en", "preferred", ""),
    ("天线耦合", "antenna-coupling", "zh", "preferred", ""),
    ("wave absorption", "wave-absorption", "en", "preferred", ""),
    ("波吸收", "wave-absorption", "zh", "preferred", ""),
    ("RF absorption", "wave-absorption", "en", "alias", ""),
    ("parallel refractive index", "n-parallel", "en", "preferred", ""),
    ("平行折射率", "n-parallel", "zh", "preferred", ""),
    ("N-parallel", "n-parallel", "en", "alias", ""),
    ("multipactor", "multipactor", "en", "preferred", ""),
    ("二次电子倍增放电", "multipactor", "zh", "preferred", ""),
    ("full-wave simulation", "full-wave-simulation", "en", "preferred", ""),
    ("全波模拟", "full-wave-simulation", "zh", "preferred", ""),
    ("antenna loading", "antenna-loading", "en", "preferred", ""),
    ("天线负载", "antenna-loading", "zh", "preferred", ""),
    ("Faraday screen", "faraday-screen", "en", "preferred", ""),
    ("法拉第屏", "faraday-screen", "zh", "preferred", ""),
    ("Faraday shield", "faraday-screen", "en", "alias", ""),
    # Batch 28: Particle Orbit Physics
    ("# ==== Batch 28: Particle Orbit Physics ====",),
    ("passing particle", "passing-particle", "en", "preferred", ""),
    ("通行粒子", "passing-particle", "zh", "preferred", ""),
    ("circulating particle", "passing-particle", "en", "alias", ""),
    ("trapped particle", "trapped-particle", "en", "preferred", ""),
    ("俘获粒子", "trapped-particle", "zh", "preferred", ""),
    ("bounce frequency", "bounce-frequency", "en", "preferred", ""),
    ("弹跳频率", "bounce-frequency", "zh", "preferred", ""),
    ("toroidal precession drift", "precession-drift", "en", "preferred", ""),
    ("进动漂移", "precession-drift", "zh", "preferred", ""),
    ("precession drift", "precession-drift", "en", "alias", ""),
    ("E×B drift", "exb-drift", "en", "preferred", ""),
    ("E×B漂移", "exb-drift", "zh", "preferred", ""),
    ("ExB drift", "exb-drift", "en", "alias", ""),
    ("grad-B drift", "grad-b-drift", "en", "preferred", ""),
    ("∇B漂移", "grad-b-drift", "zh", "preferred", ""),
    ("curvature drift", "curvature-drift", "en", "preferred", ""),
    ("曲率漂移", "curvature-drift", "zh", "preferred", ""),
    ("diamagnetic drift", "diamagnetic-drift", "en", "preferred", ""),
    ("抗磁漂移", "diamagnetic-drift", "zh", "preferred", ""),
    ("orbit loss", "orbit-loss", "en", "preferred", ""),
    ("轨道损失", "orbit-loss", "zh", "preferred", ""),
    ("fast ion loss", "orbit-loss", "en", "alias", ""),
    ("prompt loss", "prompt-loss", "en", "preferred", ""),
    ("瞬时损失", "prompt-loss", "zh", "preferred", ""),
    ("first-orbit loss", "prompt-loss", "en", "alias", ""),
    # Batch 29: Confinement Scaling & Performance Metrics
    ("# ==== Batch 29: Confinement Scaling & Performance Metrics ====",),
    ("confinement scaling law", "confinement-scaling", "en", "preferred", ""),
    ("约束标度律", "confinement-scaling", "zh", "preferred", ""),
    ("scaling law", "confinement-scaling", "en", "alias", ""),
    ("IPB98(y,2)", "confinement-scaling", "en", "alias", ""),
    ("H-factor", "h-factor", "en", "preferred", ""),
    ("H因子", "h-factor", "zh", "preferred", ""),
    ("confinement enhancement factor", "h-factor", "en", "alias", ""),
    ("Troyon limit", "troyon-limit", "en", "preferred", ""),
    ("Troyon极限", "troyon-limit", "zh", "preferred", ""),
    ("Greenwald fraction", "greenwald-fraction", "en", "preferred", ""),
    ("Greenwald份额", "greenwald-fraction", "zh", "preferred", ""),
    ("f_GW", "greenwald-fraction", "en", "alias", ""),
    ("power degradation", "power-degradation", "en", "preferred", ""),
    ("功率退化", "power-degradation", "zh", "preferred", ""),
    ("isotope effect", "isotope-effect", "en", "preferred", ""),
    ("同位素效应", "isotope-effect", "zh", "preferred", ""),
    ("size scaling", "size-scaling", "en", "preferred", ""),
    ("尺寸标度", "size-scaling", "zh", "preferred", ""),
    ("MHD stability limit", "mhd-stability-limit", "en", "preferred", ""),
    ("MHD稳定极限", "mhd-stability-limit", "zh", "preferred", ""),
    ("beta limit", "mhd-stability-limit", "en", "alias", ""),
    ("density limit", "density-limit", "en", "preferred", ""),
    ("密度极限", "density-limit", "zh", "preferred", ""),
    ("stored energy", "stored-energy", "en", "preferred", ""),
    ("等离子体储能", "stored-energy", "zh", "preferred", ""),
    ("plasma stored energy", "stored-energy", "en", "alias", ""),
    # Batch 30: Plasma Control & Actuators
    ("# ==== Batch 30: Plasma Control & Actuators ====",),
    ("vertical stability", "vertical-stability", "en", "preferred", ""),
    ("垂直稳定性", "vertical-stability", "zh", "preferred", ""),
    ("gap control", "gap-control", "en", "preferred", ""),
    ("间隙控制", "gap-control", "zh", "preferred", ""),
    ("kinetic control", "kinetic-control", "en", "preferred", ""),
    ("动理学控制", "kinetic-control", "zh", "preferred", ""),
    ("burn control", "burn-control", "en", "preferred", ""),
    ("燃烧控制", "burn-control", "zh", "preferred", ""),
    ("actuator", "actuator", "en", "preferred", ""),
    ("执行器", "actuator", "zh", "preferred", ""),
    ("plasma ramp-up", "plasma-ramp-up", "en", "preferred", ""),
    ("等离子体升流", "plasma-ramp-up", "zh", "preferred", ""),
    ("current ramp-up", "plasma-ramp-up", "en", "alias", ""),
    ("plasma ramp-down", "plasma-ramp-down", "en", "preferred", ""),
    ("等离子体降流", "plasma-ramp-down", "zh", "preferred", ""),
    ("current ramp-down", "plasma-ramp-down", "en", "alias", ""),
    ("feedback control", "feedback-control", "en", "preferred", ""),
    ("反馈控制", "feedback-control", "zh", "preferred", ""),
    ("model predictive control", "model-predictive-control", "en", "preferred", ""),
    ("MPC", "model-predictive-control", "abbr", "preferred", ""),
    ("模型预测控制", "model-predictive-control", "zh", "preferred", ""),
    ("plasma state estimation", "plasma-state-estimation", "en", "preferred", ""),
    ("等离子体状态估计", "plasma-state-estimation", "zh", "preferred", ""),
    # Batch 31: Blanket Engineering Details
    ("# ==== Batch 31: Blanket Engineering Details ====",),
    ("beryllium multiplier", "beryllium-multiplier", "en", "preferred", ""),
    ("铍中子倍增层", "beryllium-multiplier", "zh", "preferred", ""),
    ("Be multiplier", "beryllium-multiplier", "en", "alias", ""),
    ("breeding zone", "breeding-zone", "en", "preferred", ""),
    ("增殖区", "breeding-zone", "zh", "preferred", ""),
    ("back plate", "back-plate", "en", "preferred", ""),
    ("背板", "back-plate", "zh", "preferred", ""),
    ("coolant manifold", "coolant-manifold", "en", "preferred", ""),
    ("冷却歧管", "coolant-manifold", "zh", "preferred", ""),
    ("purge gas", "purge-gas", "en", "preferred", ""),
    ("吹扫气", "purge-gas", "zh", "preferred", ""),
    ("helium purge gas", "purge-gas", "en", "alias", ""),
    ("thermal fatigue", "thermal-fatigue", "en", "preferred", ""),
    ("热疲劳", "thermal-fatigue", "zh", "preferred", ""),
    # "irradiation creep" already alias of 'creep' — skipped en preferred
    ("辐照蠕变", "irradiation-creep", "zh", "preferred", ""),
    ("irradiation-enhanced creep", "irradiation-creep", "en", "preferred", ""),
    ("functional material", "functional-material", "en", "preferred", ""),
    ("功能材料", "functional-material", "zh", "preferred", ""),
    ("coolant chemistry", "coolant-chemistry", "en", "preferred", ""),
    ("冷却剂化学", "coolant-chemistry", "zh", "preferred", ""),
    ("thermo-mechanical analysis", "thermo-mechanical-analysis", "en", "preferred", ""),
    ("热机械分析", "thermo-mechanical-analysis", "zh", "preferred", ""),
    # Batch 32: Vacuum & Fueling Technology
    ("# ==== Batch 32: Vacuum & Fueling Technology ====",),
    ("vacuum pumping", "vacuum-pumping", "en", "preferred", ""),
    ("真空抽气", "vacuum-pumping", "zh", "preferred", ""),
    ("base pressure", "base-pressure", "en", "preferred", ""),
    ("本底气压", "base-pressure", "zh", "preferred", ""),
    ("outgassing", "outgassing", "en", "preferred", ""),
    ("出气", "outgassing", "zh", "preferred", ""),
    ("bakeout", "bakeout", "en", "preferred", ""),
    ("真空烘烤", "bakeout", "zh", "preferred", ""),
    ("vacuum bakeout", "bakeout", "en", "alias", ""),
    ("gas injection valve", "gas-injection-valve", "en", "preferred", ""),
    ("进气阀", "gas-injection-valve", "zh", "preferred", ""),
    ("pellet guide tube", "pellet-guide-tube", "en", "preferred", ""),
    ("弹丸导管", "pellet-guide-tube", "zh", "preferred", ""),
    ("pellet ablation", "pellet-ablation", "en", "preferred", ""),
    ("弹丸烧蚀", "pellet-ablation", "zh", "preferred", ""),
    ("cryogenic pellet", "cryogenic-pellet", "en", "preferred", ""),
    ("低温弹丸", "cryogenic-pellet", "zh", "preferred", ""),
    ("frozen pellet", "cryogenic-pellet", "en", "alias", ""),
    ("compact toroid injection", "compact-toroid-injection", "en", "preferred", ""),
    ("CTI", "compact-toroid-injection", "abbr", "preferred", ""),
    ("紧凑环注入", "compact-toroid-injection", "zh", "preferred", ""),
    ("CT injection", "compact-toroid-injection", "en", "alias", ""),
    ("gas balance", "gas-balance", "en", "preferred", ""),
    ("气体平衡", "gas-balance", "zh", "preferred", ""),
    # Batch 33: Nuclear Analysis Details
    ("# ==== Batch 33: Nuclear Analysis Details ====",),
    ("nuclear data library", "nuclear-data-library", "en", "preferred", ""),
    ("核数据库", "nuclear-data-library", "zh", "preferred", ""),
    ("contact dose rate", "contact-dose-rate", "en", "preferred", ""),
    ("接触剂量率", "contact-dose-rate", "zh", "preferred", ""),
    ("clearance index", "clearance-index", "en", "preferred", ""),
    ("清洁解控指数", "clearance-index", "zh", "preferred", ""),
    ("gas production rate", "gas-production-rate", "en", "preferred", ""),
    ("气体产额", "gas-production-rate", "zh", "preferred", ""),
    ("helium production", "helium-production", "en", "preferred", ""),
    ("氦产生", "helium-production", "zh", "preferred", ""),
    ("He production", "helium-production", "en", "alias", ""),
    ("neutron flux", "neutron-flux", "en", "preferred", ""),
    ("中子通量", "neutron-flux", "zh", "preferred", ""),
    ("photon dose", "photon-dose", "en", "preferred", ""),
    ("光子剂量", "photon-dose", "zh", "preferred", ""),
    ("gamma dose", "photon-dose", "en", "alias", ""),
    ("deep penetration", "deep-penetration", "en", "preferred", ""),
    ("深穿透", "deep-penetration", "zh", "preferred", ""),
    ("neutron streaming", "deep-penetration", "en", "alias", ""),
    ("activation foil", "activation-foil", "en", "preferred", ""),
    ("活化箔", "activation-foil", "zh", "preferred", ""),
    ("nuclear response function", "nuclear-response-function", "en", "preferred", ""),
    ("核响应函数", "nuclear-response-function", "zh", "preferred", ""),
    # Batch 34: Fusion Economics & Project Management
    ("# ==== Batch 34: Fusion Economics & Project Management ====",),
    ("first-of-a-kind", "first-of-a-kind", "en", "preferred", ""),
    ("FOAK", "first-of-a-kind", "abbr", "preferred", ""),
    ("首台堆", "first-of-a-kind", "zh", "preferred", ""),
    ("nth-of-a-kind", "nth-of-a-kind", "en", "preferred", ""),
    ("NOAK", "nth-of-a-kind", "abbr", "preferred", ""),
    ("第N台堆", "nth-of-a-kind", "zh", "preferred", ""),
    ("learning rate", "learning-rate", "en", "preferred", ""),
    ("学习率", "learning-rate", "zh", "preferred", ""),
    ("supply chain", "supply-chain", "en", "preferred", ""),
    ("供应链", "supply-chain", "zh", "preferred", ""),
    ("component qualification", "component-qualification", "en", "preferred", ""),
    ("部件鉴定", "component-qualification", "zh", "preferred", ""),
    ("prototype reactor", "prototype-reactor", "en", "preferred", ""),
    ("原型堆", "prototype-reactor", "zh", "preferred", ""),
    ("integrated commissioning", "integrated-commissioning", "en", "preferred", ""),
    ("综合调试", "integrated-commissioning", "zh", "preferred", ""),
    ("construction schedule", "construction-schedule", "en", "preferred", ""),
    ("建造进度", "construction-schedule", "zh", "preferred", ""),
    ("regulatory approval", "regulatory-approval", "en", "preferred", ""),
    ("审批许可", "regulatory-approval", "zh", "preferred", ""),
    ("decommissioning cost", "decommissioning-cost", "en", "preferred", ""),
    ("退役费用", "decommissioning-cost", "zh", "preferred", ""),
    # Batch 35: Confinement Modes & Transport Phenomena
    ("# ==== Batch 35: Confinement Modes & Transport Phenomena ====",),
    ("I-mode", "i-mode", "en", "preferred", ""),
    ("I模", "i-mode", "zh", "preferred", ""),
    ("super H-mode", "super-h-mode", "en", "preferred", ""),
    ("超级H模", "super-h-mode", "zh", "preferred", ""),
    ("density peaking", "density-peaking", "en", "preferred", ""),
    ("密度峰化", "density-peaking", "zh", "preferred", ""),
    ("impurity accumulation", "impurity-accumulation", "en", "preferred", ""),
    ("杂质积聚", "impurity-accumulation", "zh", "preferred", ""),
    ("tungsten accumulation", "tungsten-accumulation", "en", "preferred", ""),
    ("钨积聚", "tungsten-accumulation", "zh", "preferred", ""),
    ("W accumulation", "tungsten-accumulation", "en", "alias", ""),
    ("rotation reversal", "rotation-reversal", "en", "preferred", ""),
    ("旋转反转", "rotation-reversal", "zh", "preferred", ""),
    ("density pump-out", "density-pump-out", "en", "preferred", ""),
    ("密度泵出", "density-pump-out", "zh", "preferred", ""),
    ("temperature pedestal", "temperature-pedestal", "en", "preferred", ""),
    ("温度基座", "temperature-pedestal", "zh", "preferred", ""),
    ("pressure pedestal", "pressure-pedestal", "en", "preferred", ""),
    ("压力基座", "pressure-pedestal", "zh", "preferred", ""),
    ("pedestal width", "pedestal-width", "en", "preferred", ""),
    ("基座宽度", "pedestal-width", "zh", "preferred", ""),
]

EVIDENCE = [
    ("minority-heating", "internal:expansion:batch-27", "ICRF minority ion heating", "copilot", "2026-03-17"),
    ("harmonic-heating", "internal:expansion:batch-27", "Cyclotron harmonic heating", "copilot", "2026-03-17"),
    ("mode-conversion", "internal:expansion:batch-27", "Wave mode conversion", "copilot", "2026-03-17"),
    ("antenna-coupling", "internal:expansion:batch-27", "RF antenna plasma coupling", "copilot", "2026-03-17"),
    ("wave-absorption", "internal:expansion:batch-27", "Plasma RF absorption", "copilot", "2026-03-17"),
    ("n-parallel", "internal:expansion:batch-27", "Parallel refractive index", "copilot", "2026-03-17"),
    ("multipactor", "internal:expansion:batch-27", "RF secondary electron discharge", "copilot", "2026-03-17"),
    ("full-wave-simulation", "internal:expansion:batch-27", "Maxwell equation simulation", "copilot", "2026-03-17"),
    ("antenna-loading", "internal:expansion:batch-27", "Antenna impedance coupling", "copilot", "2026-03-17"),
    ("faraday-screen", "internal:expansion:batch-27", "ICRF antenna screen", "copilot", "2026-03-17"),
    ("passing-particle", "internal:expansion:batch-28", "Untrapped toroidal particle", "copilot", "2026-03-17"),
    ("trapped-particle", "internal:expansion:batch-28", "Banana orbit particle", "copilot", "2026-03-17"),
    ("bounce-frequency", "internal:expansion:batch-28", "Trapped particle oscillation", "copilot", "2026-03-17"),
    ("precession-drift", "internal:expansion:batch-28", "Toroidal precession", "copilot", "2026-03-17"),
    ("exb-drift", "internal:expansion:batch-28", "ExB particle drift", "copilot", "2026-03-17"),
    ("grad-b-drift", "internal:expansion:batch-28", "Gradient-B drift", "copilot", "2026-03-17"),
    ("curvature-drift", "internal:expansion:batch-28", "Field curvature drift", "copilot", "2026-03-17"),
    ("diamagnetic-drift", "internal:expansion:batch-28", "Pressure gradient drift", "copilot", "2026-03-17"),
    ("orbit-loss", "internal:expansion:batch-28", "Fast ion orbit loss", "copilot", "2026-03-17"),
    ("prompt-loss", "internal:expansion:batch-28", "First orbit loss", "copilot", "2026-03-17"),
    ("confinement-scaling", "internal:expansion:batch-29", "Empirical scaling law", "copilot", "2026-03-17"),
    ("h-factor", "internal:expansion:batch-29", "Confinement quality factor", "copilot", "2026-03-17"),
    ("troyon-limit", "internal:expansion:batch-29", "Beta-N stability limit", "copilot", "2026-03-17"),
    ("greenwald-fraction", "internal:expansion:batch-29", "Density / Greenwald density", "copilot", "2026-03-17"),
    ("power-degradation", "internal:expansion:batch-29", "Heating power degradation", "copilot", "2026-03-17"),
    ("isotope-effect", "internal:expansion:batch-29", "Isotope mass dependence", "copilot", "2026-03-17"),
    ("size-scaling", "internal:expansion:batch-29", "Device size scaling", "copilot", "2026-03-17"),
    ("mhd-stability-limit", "internal:expansion:batch-29", "MHD operation boundary", "copilot", "2026-03-17"),
    ("density-limit", "internal:expansion:batch-29", "Maximum density boundary", "copilot", "2026-03-17"),
    ("stored-energy", "internal:expansion:batch-29", "Plasma thermal energy", "copilot", "2026-03-17"),
    ("vertical-stability", "internal:expansion:batch-30", "Elongated plasma VDE control", "copilot", "2026-03-17"),
    ("gap-control", "internal:expansion:batch-30", "Plasma-wall gap feedback", "copilot", "2026-03-17"),
    ("kinetic-control", "internal:expansion:batch-30", "Profile active control", "copilot", "2026-03-17"),
    ("burn-control", "internal:expansion:batch-30", "Fusion burn regulation", "copilot", "2026-03-17"),
    ("actuator", "internal:expansion:batch-30", "Plasma control actuator", "copilot", "2026-03-17"),
    ("plasma-ramp-up", "internal:expansion:batch-30", "Current ramp-up phase", "copilot", "2026-03-17"),
    ("plasma-ramp-down", "internal:expansion:batch-30", "Current ramp-down phase", "copilot", "2026-03-17"),
    ("feedback-control", "internal:expansion:batch-30", "Close-loop measurement control", "copilot", "2026-03-17"),
    ("model-predictive-control", "internal:expansion:batch-30", "Model-based optimal control", "copilot", "2026-03-17"),
    ("plasma-state-estimation", "internal:expansion:batch-30", "Diagnostic state reconstruction", "copilot", "2026-03-17"),
    ("beryllium-multiplier", "internal:expansion:batch-31", "Blanket Be multiplier layer", "copilot", "2026-03-17"),
    ("breeding-zone", "internal:expansion:batch-31", "Tritium breeding region", "copilot", "2026-03-17"),
    ("back-plate", "internal:expansion:batch-31", "First wall structural support", "copilot", "2026-03-17"),
    ("coolant-manifold", "internal:expansion:batch-31", "Blanket coolant distribution", "copilot", "2026-03-17"),
    ("purge-gas", "internal:expansion:batch-31", "Tritium extraction helium", "copilot", "2026-03-17"),
    ("thermal-fatigue", "internal:expansion:batch-31", "Cyclic thermal loading fatigue", "copilot", "2026-03-17"),
    ("irradiation-creep", "internal:expansion:batch-31", "Neutron-enhanced creep", "copilot", "2026-03-17"),
    ("functional-material", "internal:expansion:batch-31", "Blanket functional materials", "copilot", "2026-03-17"),
    ("coolant-chemistry", "internal:expansion:batch-31", "Blanket coolant chemistry", "copilot", "2026-03-17"),
    ("thermo-mechanical-analysis", "internal:expansion:batch-31", "Thermal-stress coupled analysis", "copilot", "2026-03-17"),
    ("vacuum-pumping", "internal:expansion:batch-32", "VV pumping system", "copilot", "2026-03-17"),
    ("base-pressure", "internal:expansion:batch-32", "Background vacuum pressure", "copilot", "2026-03-17"),
    ("outgassing", "internal:expansion:batch-32", "Wall adsorbed gas release", "copilot", "2026-03-17"),
    ("bakeout", "internal:expansion:batch-32", "High-temperature degassing", "copilot", "2026-03-17"),
    ("gas-injection-valve", "internal:expansion:batch-32", "Fast gas valve", "copilot", "2026-03-17"),
    ("pellet-guide-tube", "internal:expansion:batch-32", "Pellet curved guide tube", "copilot", "2026-03-17"),
    ("pellet-ablation", "internal:expansion:batch-32", "Pellet surface ablation", "copilot", "2026-03-17"),
    ("cryogenic-pellet", "internal:expansion:batch-32", "Frozen fuel pellet", "copilot", "2026-03-17"),
    ("compact-toroid-injection", "internal:expansion:batch-32", "CT deep fueling", "copilot", "2026-03-17"),
    ("gas-balance", "internal:expansion:batch-32", "Device gas throughput balance", "copilot", "2026-03-17"),
    ("nuclear-data-library", "internal:expansion:batch-33", "Evaluated nuclear data", "copilot", "2026-03-17"),
    ("contact-dose-rate", "internal:expansion:batch-33", "Surface dose rate", "copilot", "2026-03-17"),
    ("clearance-index", "internal:expansion:batch-33", "Waste clearance criterion", "copilot", "2026-03-17"),
    ("gas-production-rate", "internal:expansion:batch-33", "Nuclear He/H gas rate", "copilot", "2026-03-17"),
    ("helium-production", "internal:expansion:batch-33", "Structural (n,alpha) He", "copilot", "2026-03-17"),
    ("neutron-flux", "internal:expansion:batch-33", "Neutron flow intensity", "copilot", "2026-03-17"),
    ("photon-dose", "internal:expansion:batch-33", "Secondary photon dose", "copilot", "2026-03-17"),
    ("deep-penetration", "internal:expansion:batch-33", "Shielding streaming", "copilot", "2026-03-17"),
    ("activation-foil", "internal:expansion:batch-33", "Neutron spectrum foil", "copilot", "2026-03-17"),
    ("nuclear-response-function", "internal:expansion:batch-33", "Nuclear heating response", "copilot", "2026-03-17"),
    ("first-of-a-kind", "internal:expansion:batch-34", "FOAK cost baseline", "copilot", "2026-03-17"),
    ("nth-of-a-kind", "internal:expansion:batch-34", "NOAK series cost", "copilot", "2026-03-17"),
    ("learning-rate", "internal:expansion:batch-34", "Production learning curve", "copilot", "2026-03-17"),
    ("supply-chain", "internal:expansion:batch-34", "Fusion supply chain", "copilot", "2026-03-17"),
    ("component-qualification", "internal:expansion:batch-34", "Nuclear component QA", "copilot", "2026-03-17"),
    ("prototype-reactor", "internal:expansion:batch-34", "Pre-DEMO prototype", "copilot", "2026-03-17"),
    ("integrated-commissioning", "internal:expansion:batch-34", "System-level commissioning", "copilot", "2026-03-17"),
    ("construction-schedule", "internal:expansion:batch-34", "Device build timeline", "copilot", "2026-03-17"),
    ("regulatory-approval", "internal:expansion:batch-34", "Government facility approval", "copilot", "2026-03-17"),
    ("decommissioning-cost", "internal:expansion:batch-34", "Decommission cleanup cost", "copilot", "2026-03-17"),
    ("i-mode", "internal:expansion:batch-35", "Intermediate confinement mode", "copilot", "2026-03-17"),
    ("super-h-mode", "internal:expansion:batch-35", "Wide pedestal H-mode", "copilot", "2026-03-17"),
    ("density-peaking", "internal:expansion:batch-35", "Central density peaking", "copilot", "2026-03-17"),
    ("impurity-accumulation", "internal:expansion:batch-35", "Core impurity buildup", "copilot", "2026-03-17"),
    ("tungsten-accumulation", "internal:expansion:batch-35", "Core tungsten enrichment", "copilot", "2026-03-17"),
    ("rotation-reversal", "internal:expansion:batch-35", "Spontaneous rotation reversal", "copilot", "2026-03-17"),
    ("density-pump-out", "internal:expansion:batch-35", "H-mode density transient", "copilot", "2026-03-17"),
    ("temperature-pedestal", "internal:expansion:batch-35", "Edge temperature pedestal", "copilot", "2026-03-17"),
    ("pressure-pedestal", "internal:expansion:batch-35", "Edge pressure pedestal", "copilot", "2026-03-17"),
    ("pedestal-width", "internal:expansion:batch-35", "Pedestal radial width", "copilot", "2026-03-17"),
]


def write_tsv_rows(path, rows):
    with open(path, "a", encoding="utf-8") as f:
        for row in rows:
            if len(row) == 1:
                f.write(row[0] + "\n")
            else:
                f.write(T.join(row) + "\n")


if __name__ == "__main__":
    write_tsv_rows(REG / "concepts.tsv", CONCEPTS)
    n_c = sum(1 for r in CONCEPTS if len(r) > 1)
    print(f"Appended {n_c} concepts")

    write_tsv_rows(REG / "aliases.tsv", ALIASES)
    n_a = sum(1 for r in ALIASES if len(r) > 1)
    print(f"Appended {n_a} aliases")

    write_tsv_rows(REG / "evidence.tsv", EVIDENCE)
    print(f"Appended {len(EVIDENCE)} evidence rows")
