#!/usr/bin/env python3
"""Append Batch 18-26 terms to the registry with proper TSV formatting."""

import pathlib

REG = pathlib.Path("terms/registry")
T = "\t"

CONCEPTS = [
    # Batch 18: Magnetic Equilibrium & Plasma Geometry
    ("# ==== Batch 18: Magnetic Equilibrium & Plasma Geometry ====",),
    (
        "magnetic-axis",
        "concept",
        "磁轴",
        "magnetic axis",
        "",
        "active",
        "Central line of nested flux surfaces in a toroidal plasma",
    ),
    # lcfs: SKIPPED — covered by existing 'separatrix' concept; aliases added there
    (
        "plasma-elongation",
        "metric",
        "等离子体拉长比",
        "plasma elongation",
        "",
        "active",
        "Ratio of plasma height to width (kappa), key shaping parameter",
    ),
    (
        "plasma-triangularity",
        "metric",
        "等离子体三角形变",
        "plasma triangularity",
        "",
        "active",
        "Measure of D-shape triangular deformation (delta) of plasma cross-section",
    ),
    (
        "aspect-ratio",
        "metric",
        "纵横比",
        "aspect ratio",
        "",
        "active",
        "Ratio of major radius to minor radius R/a",
    ),
    (
        "magnetic-shear",
        "metric",
        "磁剪切",
        "magnetic shear",
        "",
        "active",
        "Radial gradient of safety factor s = (r/q)(dq/dr)",
    ),
    (
        "reversed-shear",
        "concept",
        "反磁剪切",
        "reversed shear",
        "",
        "active",
        "Configuration with non-monotonic q-profile having a central minimum",
    ),
    (
        "bootstrap-fraction",
        "metric",
        "自举电流份额",
        "bootstrap fraction",
        "",
        "active",
        "Ratio of bootstrap current to total plasma current",
    ),
    (
        "pfirsch-schlueter-current",
        "concept",
        "Pfirsch-Schlüter电流",
        "Pfirsch-Schlüter current",
        "",
        "active",
        "Neoclassical current arising from pressure gradient in toroidal geometry",
    ),
    (
        "negative-triangularity",
        "concept",
        "负三角形变",
        "negative triangularity",
        "",
        "active",
        "Plasma shaping with inward-pointing D-shape, showing improved confinement",
    ),
    (
        "plasma-major-radius",
        "metric",
        "等离子体大半径",
        "plasma major radius",
        "",
        "active",
        "Distance from torus axis to magnetic axis (R0)",
    ),
    (
        "plasma-minor-radius",
        "metric",
        "等离子体小半径",
        "plasma minor radius",
        "",
        "active",
        "Half-width of the plasma cross-section (a)",
    ),
    # Batch 19: L-H Transition & Edge Transport
    ("# ==== Batch 19: L-H Transition & Edge Transport ====",),
    (
        "l-h-transition",
        "concept",
        "L-H转换",
        "L-H transition",
        "",
        "active",
        "Transition from low to high confinement mode",
    ),
    (
        "power-threshold",
        "metric",
        "功率阈值",
        "power threshold",
        "",
        "active",
        "Minimum heating power required to trigger L-H transition",
    ),
    (
        "edge-transport-barrier",
        "concept",
        "边缘输运垒",
        "edge transport barrier",
        "",
        "active",
        "Transport barrier at plasma edge associated with H-mode pedestal",
    ),
    (
        "blob-transport",
        "concept",
        "团块输运",
        "blob transport",
        "",
        "active",
        "Intermittent radial transport in SOL by filamentary structures",
    ),
    (
        "detachment-front",
        "concept",
        "脱靶前沿",
        "detachment front",
        "",
        "active",
        "Spatial boundary of the detached radiating region above divertor target",
    ),
    (
        "parallel-transport",
        "concept",
        "平行输运",
        "parallel transport",
        "",
        "active",
        "Transport along magnetic field lines",
    ),
    (
        "cross-field-transport",
        "concept",
        "垂直输运",
        "cross-field transport",
        "",
        "active",
        "Transport perpendicular to magnetic field lines across flux surfaces",
    ),
    (
        "sol-width",
        "metric",
        "SOL宽度",
        "SOL width",
        "",
        "active",
        "Power decay length in scrape-off layer (lambda_q)",
    ),
    (
        "divertor-heat-flux",
        "metric",
        "偏滤器热负荷",
        "divertor heat flux",
        "",
        "active",
        "Heat flux density on divertor target surface",
    ),
    (
        "recycling-coefficient",
        "metric",
        "再循环系数",
        "recycling coefficient",
        "",
        "active",
        "Ratio of returning particle flux to incident flux at the wall",
    ),
    # Batch 20: Plasma Waves
    ("# ==== Batch 20: Plasma Waves ====",),
    (
        "lower-hybrid-wave",
        "concept",
        "低杂波",
        "lower hybrid wave",
        "",
        "active",
        "Electrostatic-electromagnetic wave used for LHCD heating and current drive",
    ),
    (
        "electron-bernstein-wave",
        "concept",
        "电子伯恩斯坦波",
        "electron Bernstein wave",
        "EBW",
        "active",
        "Electrostatic wave for heating overdense plasmas",
    ),
    (
        "ion-bernstein-wave",
        "concept",
        "离子伯恩斯坦波",
        "ion Bernstein wave",
        "IBW",
        "active",
        "Ion-scale electrostatic wave mode for plasma heating",
    ),
    (
        "fast-wave",
        "concept",
        "快波",
        "fast wave",
        "",
        "active",
        "Fast magnetosonic wave used in ICRF heating",
    ),
    (
        "slow-wave",
        "concept",
        "慢波",
        "slow wave",
        "",
        "active",
        "Slow electrostatic wave branch in lower hybrid range",
    ),
    (
        "alfven-continuum",
        "concept",
        "Alfvén连续谱",
        "Alfvén continuum",
        "",
        "active",
        "Continuous spectrum of shear Alfvén waves in toroidal geometry",
    ),
    (
        "rsae",
        "concept",
        "反剪切Alfvén本征模",
        "reversed shear Alfvén eigenmode",
        "RSAE",
        "active",
        "Gap mode in reversed shear region, also called Alfvén cascade",
    ),
    (
        "bae",
        "concept",
        "β诱导Alfvén本征模",
        "beta-induced Alfvén eigenmode",
        "BAE",
        "active",
        "Alfvén eigenmode in the beta-induced gap of the continuum",
    ),
    (
        "energetic-particle-mode",
        "concept",
        "高能粒子模",
        "energetic particle mode",
        "EPM",
        "active",
        "Non-perturbative fast-ion driven mode in the Alfvén continuum",
    ),
    (
        "parametric-instability",
        "concept",
        "参数不稳定性",
        "parametric instability",
        "",
        "active",
        "Nonlinear laser-plasma coupling instability important in ICF",
    ),
    # Batch 21: Fusion Reactions & Nuclear Physics
    ("# ==== Batch 21: Fusion Reactions & Nuclear Physics ====",),
    (
        "dt-reaction",
        "concept",
        "D-T反应",
        "D-T reaction",
        "",
        "active",
        "Deuterium-tritium fusion reaction producing 14.1 MeV neutron and 3.5 MeV alpha",
    ),
    (
        "dd-reaction",
        "concept",
        "D-D反应",
        "D-D reaction",
        "",
        "active",
        "Deuterium-deuterium fusion with two branches producing T+p or He3+n",
    ),
    (
        "d-he3-reaction",
        "concept",
        "D-³He反应",
        "D-³He reaction",
        "",
        "active",
        "Low-neutron advanced fuel fusion reaction producing proton and alpha",
    ),
    (
        "fusion-triple-product",
        "metric",
        "聚变三乘积",
        "fusion triple product",
        "",
        "active",
        "Product n·T·tau_E used as figure of merit for fusion ignition conditions",
    ),
    # 14mev-neutron: SKIPPED — covered by existing 'fusion-neutron' concept
    (
        "neutron-yield",
        "metric",
        "中子产额",
        "neutron yield",
        "",
        "active",
        "Total number or rate of fusion neutrons produced",
    ),
    (
        "reaction-rate-coefficient",
        "metric",
        "反应速率系数",
        "reaction rate coefficient",
        "",
        "active",
        "Maxwellian-averaged fusion reactivity <sigma*v>",
    ),
    (
        "q-value-reaction",
        "metric",
        "Q值",
        "Q value",
        "",
        "active",
        "Energy released per fusion reaction",
    ),
    (
        "coulomb-logarithm",
        "metric",
        "库仑对数",
        "Coulomb logarithm",
        "",
        "active",
        "Logarithmic factor in Coulomb collision frequency",
    ),
    (
        "slowing-down-time",
        "metric",
        "滑脱时间",
        "slowing-down time",
        "",
        "active",
        "Characteristic time for fast ion thermalization via collisions",
    ),
    # Batch 22: Advanced Tokamak & Operational Scenarios
    ("# ==== Batch 22: Advanced Tokamak & Operational Scenarios ====",),
    (
        "current-hole",
        "concept",
        "电流空洞",
        "current hole",
        "",
        "active",
        "Region of nearly zero toroidal current density near plasma center",
    ),
    (
        "internal-kink-mode",
        "concept",
        "内扭曲模",
        "internal kink mode",
        "",
        "active",
        "m=1/n=1 MHD instability inside q=1 surface",
    ),
    (
        "sawtooth-crash",
        "concept",
        "锯齿崩塌",
        "sawtooth crash",
        "",
        "active",
        "Periodic crash phase of sawtooth oscillation flattening central profiles",
    ),
    (
        "ntv",
        "concept",
        "新经典环向粘滞",
        "neoclassical toroidal viscosity",
        "NTV",
        "active",
        "Plasma braking torque from non-axisymmetric magnetic fields",
    ),
    (
        "intrinsic-rotation",
        "concept",
        "本征旋转",
        "intrinsic rotation",
        "",
        "active",
        "Spontaneous plasma rotation without external momentum input",
    ),
    (
        "momentum-transport",
        "concept",
        "动量输运",
        "momentum transport",
        "",
        "active",
        "Radial transport of toroidal angular momentum",
    ),
    (
        "profile-stiffness",
        "concept",
        "剖面刚性",
        "profile stiffness",
        "",
        "active",
        "Tendency of transport to maintain profiles near critical gradient",
    ),
    (
        "critical-gradient",
        "concept",
        "临界梯度",
        "critical gradient",
        "",
        "active",
        "Threshold gradient above which micro-instabilities drive strong transport",
    ),
    (
        "fully-non-inductive",
        "concept",
        "完全非感应运行",
        "fully non-inductive operation",
        "",
        "active",
        "Steady-state operation with 100% non-inductive current drive",
    ),
    (
        "steady-state-high-beta",
        "concept",
        "稳态高β运行",
        "steady-state high-beta operation",
        "",
        "active",
        "Advanced tokamak target scenario combining high beta with steady state",
    ),
    # Batch 23: Superconducting Magnet Engineering
    ("# ==== Batch 23: Superconducting Magnet Engineering ====",),
    (
        "ac-loss",
        "concept",
        "交流损耗",
        "AC loss",
        "",
        "active",
        "Heat generation in superconductor from time-varying magnetic fields",
    ),
    (
        "strain-sensitivity",
        "concept",
        "应变敏感性",
        "strain sensitivity",
        "",
        "active",
        "Dependence of critical current on mechanical strain in Nb3Sn conductors",
    ),
    (
        "joint-resistance",
        "metric",
        "接头电阻",
        "joint resistance",
        "",
        "active",
        "Electrical resistance at superconducting cable joints",
    ),
    (
        "tf-ripple",
        "concept",
        "环向场纹波",
        "toroidal field ripple",
        "",
        "active",
        "Periodic variation of toroidal field due to finite number of TF coils",
    ),
    (
        "demountable-joint",
        "system",
        "可拆卸接头",
        "demountable joint",
        "",
        "active",
        "Separable superconducting joint enabling modular magnet maintenance",
    ),
    (
        "magnet-bore",
        "metric",
        "磁体孔径",
        "magnet bore",
        "",
        "active",
        "Clear internal opening of toroidal field coil",
    ),
    (
        "winding-pack",
        "system",
        "绕组包",
        "winding pack",
        "",
        "active",
        "Assembly of superconducting cable turns forming the magnet coil",
    ),
    (
        "magnet-structure",
        "system",
        "磁体结构件",
        "magnet structure",
        "",
        "active",
        "Structural casing and support for superconducting coils",
    ),
    (
        "insulation-material",
        "material",
        "绝缘材料",
        "insulation material",
        "",
        "active",
        "Turn-to-turn and layer-to-layer electrical insulation in magnet windings",
    ),
    (
        "magnet-cooling",
        "system",
        "磁体冷却",
        "magnet cooling",
        "",
        "active",
        "Cryogenic cooling system maintaining superconducting operating temperature",
    ),
    # Batch 24: Plasma-Wall Interaction Details
    ("# ==== Batch 24: Plasma-Wall Interaction Details ====",),
    (
        "chemical-erosion",
        "concept",
        "化学腐蚀",
        "chemical erosion",
        "",
        "active",
        "Erosion of carbon materials via chemical reaction with hydrogen isotopes",
    ),
    (
        "physical-sputtering",
        "concept",
        "物理溅射",
        "physical sputtering",
        "",
        "active",
        "Surface atom ejection by energetic ion bombardment",
    ),
    (
        "dust",
        "concept",
        "粉尘",
        "dust",
        "",
        "active",
        "Micron-scale particulates generated from PFC erosion and disruptions",
    ),
    (
        "arcing",
        "concept",
        "电弧",
        "arcing",
        "",
        "active",
        "Localized arc discharge between plasma and wall surface causing damage",
    ),
    (
        "melt-damage",
        "concept",
        "熔化损伤",
        "melt damage",
        "",
        "active",
        "PFC surface melting from transient high heat loads",
    ),
    (
        "mixed-material",
        "concept",
        "混合材料",
        "mixed material",
        "",
        "active",
        "Co-deposited layers of multiple PFC materials (e.g. Be-W)",
    ),
    (
        "wall-conditioning",
        "method",
        "壁面处理",
        "wall conditioning",
        "",
        "active",
        "Surface preparation techniques for impurity control before plasma operation",
    ),
    (
        "glow-discharge-cleaning",
        "method",
        "辉光放电清洗",
        "glow discharge cleaning",
        "GDC",
        "active",
        "Low-pressure gas discharge technique for vessel wall cleaning",
    ),
    (
        "boronization",
        "method",
        "硼化",
        "boronization",
        "",
        "active",
        "Deposition of thin boron film on vessel walls for impurity control",
    ),
    (
        "tritium-removal",
        "method",
        "氚滞留清除",
        "tritium removal",
        "",
        "active",
        "Techniques for removing retained tritium from PFCs",
    ),
    # Batch 25: Computational Physics Methods
    ("# ==== Batch 25: Computational Physics Methods ====",),
    (
        "fokker-planck-equation",
        "concept",
        "Fokker-Planck方程",
        "Fokker-Planck equation",
        "",
        "active",
        "Kinetic equation describing collisional evolution of particle distribution function",
    ),
    (
        "vlasov-equation",
        "concept",
        "Vlasov方程",
        "Vlasov equation",
        "",
        "active",
        "Collisionless kinetic equation for plasma distribution function",
    ),
    (
        "ray-tracing",
        "method",
        "射线追踪",
        "ray tracing",
        "",
        "active",
        "Geometrical optics method for computing wave propagation and power deposition",
    ),
    (
        "flux-tube-simulation",
        "method",
        "磁通管模拟",
        "flux tube simulation",
        "",
        "active",
        "Local gyrokinetic simulation in a field-aligned flux tube domain",
    ),
    (
        "reduced-mhd",
        "concept",
        "约化MHD",
        "reduced MHD",
        "",
        "active",
        "Simplified MHD model valid for low-beta, large-aspect-ratio plasmas",
    ),
    (
        "extended-mhd",
        "concept",
        "扩展MHD",
        "extended MHD",
        "",
        "active",
        "MHD model including two-fluid, FLR, and kinetic closure effects",
    ),
    (
        "two-fluid-model",
        "concept",
        "双流体模型",
        "two-fluid model",
        "",
        "active",
        "Plasma model treating electrons and ions as separate coupled fluids",
    ),
    (
        "delta-f-method",
        "method",
        "δf方法",
        "delta-f method",
        "",
        "active",
        "PIC noise reduction technique evolving only the perturbed distribution",
    ),
    (
        "full-f-method",
        "method",
        "全f方法",
        "full-f method",
        "",
        "active",
        "PIC method evolving the complete distribution function",
    ),
    (
        "continuum-kinetic",
        "method",
        "连续谱动理学",
        "continuum kinetic",
        "",
        "active",
        "Direct discretization of Vlasov equation on phase-space grid",
    ),
    # Batch 26: Safety, Regulation & Standards
    ("# ==== Batch 26: Safety, Regulation & Standards ====",),
    (
        "defense-in-depth",
        "concept",
        "纵深防御",
        "defense in depth",
        "",
        "active",
        "Multi-layered safety design philosophy for nuclear facilities",
    ),
    (
        "safety-classification",
        "concept",
        "安全分级",
        "safety classification",
        "",
        "active",
        "Categorization of systems by their safety importance",
    ),
    (
        "iaea",
        "organization",
        "国际原子能机构",
        "International Atomic Energy Agency",
        "IAEA",
        "active",
        "UN agency for peaceful nuclear technology and safeguards",
    ),
    (
        "confinement-function",
        "concept",
        "包容功能",
        "confinement function",
        "",
        "active",
        "Safety function providing containment barriers for radioactive materials",
    ),
    (
        "maximum-credible-accident",
        "concept",
        "最大可信事故",
        "maximum credible accident",
        "",
        "active",
        "Most severe postulated accident scenario for safety analysis",
    ),
    (
        "source-term",
        "concept",
        "源项",
        "source term",
        "",
        "active",
        "Quantification of radioactive material released in accident scenarios",
    ),
    (
        "emergency-planning-zone",
        "concept",
        "应急计划区",
        "emergency planning zone",
        "EPZ",
        "active",
        "Designated area for emergency response planning around nuclear facility",
    ),
    (
        "occupational-dose-limit",
        "limit",
        "职业剂量限值",
        "occupational dose limit",
        "",
        "active",
        "Annual dose limit for radiation workers",
    ),
]

ALIASES = [
    # Batch 18
    ("# ==== Batch 18: Magnetic Equilibrium & Plasma Geometry ====",),
    ("magnetic axis", "magnetic-axis", "en", "preferred", ""),
    ("磁轴", "magnetic-axis", "zh", "preferred", ""),
    ("last closed flux surface", "separatrix", "en", "alias", "LCFS redirect"),
    ("LCFS", "separatrix", "abbr", "alias", "LCFS redirect"),
    # 最后闭合磁面 already exists for separatrix — skipped
    ("plasma boundary", "separatrix", "en", "alias", "LCFS redirect"),
    ("plasma elongation", "plasma-elongation", "en", "preferred", ""),
    ("等离子体拉长比", "plasma-elongation", "zh", "preferred", ""),
    ("elongation", "plasma-elongation", "en", "alias", ""),
    ("plasma triangularity", "plasma-triangularity", "en", "preferred", ""),
    ("等离子体三角形变", "plasma-triangularity", "zh", "preferred", ""),
    ("triangularity", "plasma-triangularity", "en", "alias", ""),
    ("aspect ratio", "aspect-ratio", "en", "preferred", ""),
    ("纵横比", "aspect-ratio", "zh", "preferred", ""),
    ("magnetic shear", "magnetic-shear", "en", "preferred", ""),
    ("磁剪切", "magnetic-shear", "zh", "preferred", ""),
    ("reversed shear", "reversed-shear", "en", "preferred", ""),
    ("反磁剪切", "reversed-shear", "zh", "preferred", ""),
    ("reverse shear", "reversed-shear", "en", "alias", ""),
    ("bootstrap fraction", "bootstrap-fraction", "en", "preferred", ""),
    ("自举电流份额", "bootstrap-fraction", "zh", "preferred", ""),
    ("Pfirsch-Schlüter current", "pfirsch-schlueter-current", "en", "preferred", ""),
    ("Pfirsch-Schlüter电流", "pfirsch-schlueter-current", "zh", "preferred", ""),
    ("PS current", "pfirsch-schlueter-current", "en", "alias", ""),
    ("negative triangularity", "negative-triangularity", "en", "preferred", ""),
    ("负三角形变", "negative-triangularity", "zh", "preferred", ""),
    ("NT", "negative-triangularity", "abbr", "alias", ""),
    ("plasma major radius", "plasma-major-radius", "en", "preferred", ""),
    ("等离子体大半径", "plasma-major-radius", "zh", "preferred", ""),
    ("major radius", "plasma-major-radius", "en", "alias", ""),
    ("plasma minor radius", "plasma-minor-radius", "en", "preferred", ""),
    ("等离子体小半径", "plasma-minor-radius", "zh", "preferred", ""),
    ("minor radius", "plasma-minor-radius", "en", "alias", ""),
    # Batch 19
    ("# ==== Batch 19: L-H Transition & Edge Transport ====",),
    ("L-H transition", "l-h-transition", "en", "preferred", ""),
    ("L-H转换", "l-h-transition", "zh", "preferred", ""),
    ("L-to-H transition", "l-h-transition", "en", "alias", ""),
    ("power threshold", "power-threshold", "en", "preferred", ""),
    ("功率阈值", "power-threshold", "zh", "preferred", ""),
    ("L-H power threshold", "power-threshold", "en", "alias", ""),
    ("edge transport barrier", "edge-transport-barrier", "en", "preferred", ""),
    ("边缘输运垒", "edge-transport-barrier", "zh", "preferred", ""),
    ("ETB", "edge-transport-barrier", "abbr", "alias", ""),
    ("blob transport", "blob-transport", "en", "preferred", ""),
    ("团块输运", "blob-transport", "zh", "preferred", ""),
    ("filamentary transport", "blob-transport", "en", "alias", ""),
    ("detachment front", "detachment-front", "en", "preferred", ""),
    ("脱靶前沿", "detachment-front", "zh", "preferred", ""),
    ("parallel transport", "parallel-transport", "en", "preferred", ""),
    ("平行输运", "parallel-transport", "zh", "preferred", ""),
    ("cross-field transport", "cross-field-transport", "en", "preferred", ""),
    ("垂直输运", "cross-field-transport", "zh", "preferred", ""),
    ("perpendicular transport", "cross-field-transport", "en", "alias", ""),
    ("SOL width", "sol-width", "en", "preferred", ""),
    ("SOL宽度", "sol-width", "zh", "preferred", ""),
    ("lambda_q", "sol-width", "en", "alias", ""),
    ("divertor heat flux", "divertor-heat-flux", "en", "preferred", ""),
    ("偏滤器热负荷", "divertor-heat-flux", "zh", "preferred", ""),
    ("recycling coefficient", "recycling-coefficient", "en", "preferred", ""),
    ("再循环系数", "recycling-coefficient", "zh", "preferred", ""),
    # Batch 20
    ("# ==== Batch 20: Plasma Waves ====",),
    ("lower hybrid wave", "lower-hybrid-wave", "en", "preferred", ""),
    ("低杂波", "lower-hybrid-wave", "zh", "preferred", ""),
    ("LH wave", "lower-hybrid-wave", "en", "alias", ""),
    ("electron Bernstein wave", "electron-bernstein-wave", "en", "preferred", ""),
    ("EBW", "electron-bernstein-wave", "abbr", "preferred", ""),
    ("电子伯恩斯坦波", "electron-bernstein-wave", "zh", "preferred", ""),
    ("ion Bernstein wave", "ion-bernstein-wave", "en", "preferred", ""),
    ("IBW", "ion-bernstein-wave", "abbr", "preferred", ""),
    ("离子伯恩斯坦波", "ion-bernstein-wave", "zh", "preferred", ""),
    ("fast wave", "fast-wave", "en", "preferred", ""),
    ("快波", "fast-wave", "zh", "preferred", ""),
    ("fast magnetosonic wave", "fast-wave", "en", "alias", ""),
    ("slow wave", "slow-wave", "en", "preferred", ""),
    ("慢波", "slow-wave", "zh", "preferred", ""),
    ("Alfvén continuum", "alfven-continuum", "en", "preferred", ""),
    ("Alfvén连续谱", "alfven-continuum", "zh", "preferred", ""),
    ("reversed shear Alfvén eigenmode", "rsae", "en", "preferred", ""),
    ("RSAE", "rsae", "abbr", "preferred", ""),
    ("反剪切Alfvén本征模", "rsae", "zh", "preferred", ""),
    ("Alfvén cascade", "rsae", "en", "alias", ""),
    ("beta-induced Alfvén eigenmode", "bae", "en", "preferred", ""),
    ("BAE", "bae", "abbr", "preferred", ""),
    ("β诱导Alfvén本征模", "bae", "zh", "preferred", ""),
    ("energetic particle mode", "energetic-particle-mode", "en", "preferred", ""),
    ("EPM", "energetic-particle-mode", "abbr", "preferred", ""),
    ("高能粒子模", "energetic-particle-mode", "zh", "preferred", ""),
    ("parametric instability", "parametric-instability", "en", "preferred", ""),
    ("参数不稳定性", "parametric-instability", "zh", "preferred", ""),
    # Batch 21
    ("# ==== Batch 21: Fusion Reactions & Nuclear Physics ====",),
    ("D-T reaction", "dt-reaction", "en", "preferred", ""),
    ("D-T反应", "dt-reaction", "zh", "preferred", ""),
    ("deuterium-tritium reaction", "dt-reaction", "en", "alias", ""),
    ("氘氚反应", "dt-reaction", "zh", "alias", ""),
    ("D-D reaction", "dd-reaction", "en", "preferred", ""),
    ("D-D反应", "dd-reaction", "zh", "preferred", ""),
    ("deuterium-deuterium reaction", "dd-reaction", "en", "alias", ""),
    ("氘氘反应", "dd-reaction", "zh", "alias", ""),
    ("D-³He reaction", "d-he3-reaction", "en", "preferred", ""),
    ("D-³He反应", "d-he3-reaction", "zh", "preferred", ""),
    ("fusion triple product", "fusion-triple-product", "en", "preferred", ""),
    ("聚变三乘积", "fusion-triple-product", "zh", "preferred", ""),
    # 14 MeV neutron: already exists as alias for fusion-neutron — skipped
    ("14 MeV中子", "fusion-neutron", "zh", "alias", "14mev redirect"),
    ("neutron yield", "neutron-yield", "en", "preferred", ""),
    ("中子产额", "neutron-yield", "zh", "preferred", ""),
    ("reaction rate coefficient", "reaction-rate-coefficient", "en", "preferred", ""),
    ("反应速率系数", "reaction-rate-coefficient", "zh", "preferred", ""),
    ("sigma-v", "reaction-rate-coefficient", "en", "alias", ""),
    ("Q value", "q-value-reaction", "en", "preferred", ""),
    ("Q值", "q-value-reaction", "zh", "preferred", ""),
    ("Coulomb logarithm", "coulomb-logarithm", "en", "preferred", ""),
    ("库仑对数", "coulomb-logarithm", "zh", "preferred", ""),
    ("slowing-down time", "slowing-down-time", "en", "preferred", ""),
    ("滑脱时间", "slowing-down-time", "zh", "preferred", ""),
    ("thermalization time", "slowing-down-time", "en", "alias", ""),
    # Batch 22
    ("# ==== Batch 22: Advanced Tokamak & Operational Scenarios ====",),
    ("current hole", "current-hole", "en", "preferred", ""),
    ("电流空洞", "current-hole", "zh", "preferred", ""),
    ("internal kink mode", "internal-kink-mode", "en", "preferred", ""),
    ("内扭曲模", "internal-kink-mode", "zh", "preferred", ""),
    ("m=1 mode", "internal-kink-mode", "en", "alias", ""),
    ("sawtooth crash", "sawtooth-crash", "en", "preferred", ""),
    ("锯齿崩塌", "sawtooth-crash", "zh", "preferred", ""),
    ("neoclassical toroidal viscosity", "ntv", "en", "preferred", ""),
    ("NTV", "ntv", "abbr", "preferred", ""),
    ("新经典环向粘滞", "ntv", "zh", "preferred", ""),
    ("intrinsic rotation", "intrinsic-rotation", "en", "preferred", ""),
    ("本征旋转", "intrinsic-rotation", "zh", "preferred", ""),
    ("spontaneous rotation", "intrinsic-rotation", "en", "alias", ""),
    ("momentum transport", "momentum-transport", "en", "preferred", ""),
    ("动量输运", "momentum-transport", "zh", "preferred", ""),
    ("profile stiffness", "profile-stiffness", "en", "preferred", ""),
    ("剖面刚性", "profile-stiffness", "zh", "preferred", ""),
    ("critical gradient", "critical-gradient", "en", "preferred", ""),
    ("临界梯度", "critical-gradient", "zh", "preferred", ""),
    ("fully non-inductive operation", "fully-non-inductive", "en", "preferred", ""),
    ("完全非感应运行", "fully-non-inductive", "zh", "preferred", ""),
    (
        "steady-state high-beta operation",
        "steady-state-high-beta",
        "en",
        "preferred",
        "",
    ),
    ("稳态高β运行", "steady-state-high-beta", "zh", "preferred", ""),
    # Batch 23
    ("# ==== Batch 23: Superconducting Magnet Engineering ====",),
    ("AC loss", "ac-loss", "en", "preferred", ""),
    ("交流损耗", "ac-loss", "zh", "preferred", ""),
    ("strain sensitivity", "strain-sensitivity", "en", "preferred", ""),
    ("应变敏感性", "strain-sensitivity", "zh", "preferred", ""),
    ("joint resistance", "joint-resistance", "en", "preferred", ""),
    ("接头电阻", "joint-resistance", "zh", "preferred", ""),
    ("toroidal field ripple", "tf-ripple", "en", "preferred", ""),
    ("环向场纹波", "tf-ripple", "zh", "preferred", ""),
    ("TF ripple", "tf-ripple", "en", "alias", ""),
    ("demountable joint", "demountable-joint", "en", "preferred", ""),
    ("可拆卸接头", "demountable-joint", "zh", "preferred", ""),
    ("magnet bore", "magnet-bore", "en", "preferred", ""),
    ("磁体孔径", "magnet-bore", "zh", "preferred", ""),
    ("winding pack", "winding-pack", "en", "preferred", ""),
    ("绕组包", "winding-pack", "zh", "preferred", ""),
    ("magnet structure", "magnet-structure", "en", "preferred", ""),
    ("磁体结构件", "magnet-structure", "zh", "preferred", ""),
    ("insulation material", "insulation-material", "en", "preferred", ""),
    ("绝缘材料", "insulation-material", "zh", "preferred", ""),
    ("magnet cooling", "magnet-cooling", "en", "preferred", ""),
    ("磁体冷却", "magnet-cooling", "zh", "preferred", ""),
    # Batch 24
    ("# ==== Batch 24: Plasma-Wall Interaction Details ====",),
    ("chemical erosion", "chemical-erosion", "en", "preferred", ""),
    ("化学腐蚀", "chemical-erosion", "zh", "preferred", ""),
    # chemical sputtering: already alias of 'sputtering' — skipped
    # 物理溅射: already alias of 'sputtering' — skipped
    ("physical sputtering", "physical-sputtering", "en", "preferred", ""),
    ("dust", "dust", "en", "preferred", ""),
    ("粉尘", "dust", "zh", "preferred", ""),
    ("fusion dust", "dust", "en", "alias", ""),
    ("arcing", "arcing", "en", "preferred", ""),
    ("电弧", "arcing", "zh", "preferred", ""),
    ("unipolar arc", "arcing", "en", "alias", ""),
    ("melt damage", "melt-damage", "en", "preferred", ""),
    ("熔化损伤", "melt-damage", "zh", "preferred", ""),
    ("mixed material", "mixed-material", "en", "preferred", ""),
    ("混合材料", "mixed-material", "zh", "preferred", ""),
    ("co-deposited layer", "mixed-material", "en", "alias", ""),
    ("wall conditioning", "wall-conditioning", "en", "preferred", ""),
    ("壁面处理", "wall-conditioning", "zh", "preferred", ""),
    ("glow discharge cleaning", "glow-discharge-cleaning", "en", "preferred", ""),
    ("GDC", "glow-discharge-cleaning", "abbr", "preferred", ""),
    ("辉光放电清洗", "glow-discharge-cleaning", "zh", "preferred", ""),
    ("boronization", "boronization", "en", "preferred", ""),
    ("硼化", "boronization", "zh", "preferred", ""),
    ("tritium removal", "tritium-removal", "en", "preferred", ""),
    ("氚滞留清除", "tritium-removal", "zh", "preferred", ""),
    # Batch 25
    ("# ==== Batch 25: Computational Physics Methods ====",),
    ("Fokker-Planck equation", "fokker-planck-equation", "en", "preferred", ""),
    ("Fokker-Planck方程", "fokker-planck-equation", "zh", "preferred", ""),
    ("Vlasov equation", "vlasov-equation", "en", "preferred", ""),
    ("Vlasov方程", "vlasov-equation", "zh", "preferred", ""),
    ("ray tracing", "ray-tracing", "en", "preferred", ""),
    ("射线追踪", "ray-tracing", "zh", "preferred", ""),
    ("flux tube simulation", "flux-tube-simulation", "en", "preferred", ""),
    ("磁通管模拟", "flux-tube-simulation", "zh", "preferred", ""),
    ("local gyrokinetic simulation", "flux-tube-simulation", "en", "alias", ""),
    ("reduced MHD", "reduced-mhd", "en", "preferred", ""),
    ("约化MHD", "reduced-mhd", "zh", "preferred", ""),
    ("extended MHD", "extended-mhd", "en", "preferred", ""),
    ("扩展MHD", "extended-mhd", "zh", "preferred", ""),
    ("two-fluid model", "two-fluid-model", "en", "preferred", ""),
    ("双流体模型", "two-fluid-model", "zh", "preferred", ""),
    ("delta-f method", "delta-f-method", "en", "preferred", ""),
    ("δf方法", "delta-f-method", "zh", "preferred", ""),
    ("full-f method", "full-f-method", "en", "preferred", ""),
    ("全f方法", "full-f-method", "zh", "preferred", ""),
    ("continuum kinetic", "continuum-kinetic", "en", "preferred", ""),
    ("连续谱动理学", "continuum-kinetic", "zh", "preferred", ""),
    ("Eulerian kinetic", "continuum-kinetic", "en", "alias", ""),
    # Batch 26
    ("# ==== Batch 26: Safety, Regulation & Standards ====",),
    ("defense in depth", "defense-in-depth", "en", "preferred", ""),
    ("纵深防御", "defense-in-depth", "zh", "preferred", ""),
    ("safety classification", "safety-classification", "en", "preferred", ""),
    ("安全分级", "safety-classification", "zh", "preferred", ""),
    ("International Atomic Energy Agency", "iaea", "en", "preferred", ""),
    ("IAEA", "iaea", "abbr", "preferred", ""),
    ("国际原子能机构", "iaea", "zh", "preferred", ""),
    ("confinement function", "confinement-function", "en", "preferred", ""),
    ("包容功能", "confinement-function", "zh", "preferred", ""),
    ("containment function", "confinement-function", "en", "alias", ""),
    ("maximum credible accident", "maximum-credible-accident", "en", "preferred", ""),
    ("最大可信事故", "maximum-credible-accident", "zh", "preferred", ""),
    ("MCA", "maximum-credible-accident", "abbr", "alias", ""),
    ("source term", "source-term", "en", "preferred", ""),
    ("源项", "source-term", "zh", "preferred", ""),
    ("emergency planning zone", "emergency-planning-zone", "en", "preferred", ""),
    ("EPZ", "emergency-planning-zone", "abbr", "preferred", ""),
    ("应急计划区", "emergency-planning-zone", "zh", "preferred", ""),
    ("occupational dose limit", "occupational-dose-limit", "en", "preferred", ""),
    ("职业剂量限值", "occupational-dose-limit", "zh", "preferred", ""),
]

EVIDENCE = [
    (
        "magnetic-axis",
        "internal:expansion:batch-18",
        "Nested flux surface center",
        "copilot",
        "2026-03-17",
    ),
    # lcfs: evidence skipped — merged into existing separatrix concept
    (
        "plasma-elongation",
        "internal:expansion:batch-18",
        "Plasma height-to-width ratio",
        "copilot",
        "2026-03-17",
    ),
    (
        "plasma-triangularity",
        "internal:expansion:batch-18",
        "D-shape deformation parameter",
        "copilot",
        "2026-03-17",
    ),
    (
        "aspect-ratio",
        "internal:expansion:batch-18",
        "Major-to-minor radius ratio",
        "copilot",
        "2026-03-17",
    ),
    (
        "magnetic-shear",
        "internal:expansion:batch-18",
        "Safety factor radial gradient",
        "copilot",
        "2026-03-17",
    ),
    (
        "reversed-shear",
        "internal:expansion:batch-18",
        "Non-monotonic q-profile",
        "copilot",
        "2026-03-17",
    ),
    (
        "bootstrap-fraction",
        "internal:expansion:batch-18",
        "Bootstrap current ratio",
        "copilot",
        "2026-03-17",
    ),
    (
        "pfirsch-schlueter-current",
        "internal:expansion:batch-18",
        "Neoclassical equilibrium current",
        "copilot",
        "2026-03-17",
    ),
    (
        "negative-triangularity",
        "internal:expansion:batch-18",
        "Inward D-shape configuration",
        "copilot",
        "2026-03-17",
    ),
    (
        "plasma-major-radius",
        "internal:expansion:batch-18",
        "Torus major radius R0",
        "copilot",
        "2026-03-17",
    ),
    (
        "plasma-minor-radius",
        "internal:expansion:batch-18",
        "Plasma half-width a",
        "copilot",
        "2026-03-17",
    ),
    (
        "l-h-transition",
        "internal:expansion:batch-19",
        "L-to-H mode transition",
        "copilot",
        "2026-03-17",
    ),
    (
        "power-threshold",
        "internal:expansion:batch-19",
        "L-H transition power threshold",
        "copilot",
        "2026-03-17",
    ),
    (
        "edge-transport-barrier",
        "internal:expansion:batch-19",
        "H-mode pedestal barrier",
        "copilot",
        "2026-03-17",
    ),
    (
        "blob-transport",
        "internal:expansion:batch-19",
        "SOL filamentary transport",
        "copilot",
        "2026-03-17",
    ),
    (
        "detachment-front",
        "internal:expansion:batch-19",
        "Detached region boundary",
        "copilot",
        "2026-03-17",
    ),
    (
        "parallel-transport",
        "internal:expansion:batch-19",
        "Field-aligned transport",
        "copilot",
        "2026-03-17",
    ),
    (
        "cross-field-transport",
        "internal:expansion:batch-19",
        "Perpendicular transport",
        "copilot",
        "2026-03-17",
    ),
    (
        "sol-width",
        "internal:expansion:batch-19",
        "SOL power decay length",
        "copilot",
        "2026-03-17",
    ),
    (
        "divertor-heat-flux",
        "internal:expansion:batch-19",
        "Target surface heat flux",
        "copilot",
        "2026-03-17",
    ),
    (
        "recycling-coefficient",
        "internal:expansion:batch-19",
        "Wall particle recycling ratio",
        "copilot",
        "2026-03-17",
    ),
    (
        "lower-hybrid-wave",
        "internal:expansion:batch-20",
        "LH wave for heating/CD",
        "copilot",
        "2026-03-17",
    ),
    (
        "electron-bernstein-wave",
        "internal:expansion:batch-20",
        "Overdense plasma wave",
        "copilot",
        "2026-03-17",
    ),
    (
        "ion-bernstein-wave",
        "internal:expansion:batch-20",
        "Ion-scale electrostatic wave",
        "copilot",
        "2026-03-17",
    ),
    (
        "fast-wave",
        "internal:expansion:batch-20",
        "ICRF fast magnetosonic wave",
        "copilot",
        "2026-03-17",
    ),
    (
        "slow-wave",
        "internal:expansion:batch-20",
        "LH range slow wave branch",
        "copilot",
        "2026-03-17",
    ),
    (
        "alfven-continuum",
        "internal:expansion:batch-20",
        "Shear Alfven continuum",
        "copilot",
        "2026-03-17",
    ),
    (
        "rsae",
        "internal:expansion:batch-20",
        "Reversed shear gap mode",
        "copilot",
        "2026-03-17",
    ),
    (
        "bae",
        "internal:expansion:batch-20",
        "Beta-induced gap eigenmode",
        "copilot",
        "2026-03-17",
    ),
    (
        "energetic-particle-mode",
        "internal:expansion:batch-20",
        "Fast-ion driven continuum mode",
        "copilot",
        "2026-03-17",
    ),
    (
        "parametric-instability",
        "internal:expansion:batch-20",
        "Laser-plasma nonlinear coupling",
        "copilot",
        "2026-03-17",
    ),
    (
        "dt-reaction",
        "internal:expansion:batch-21",
        "D-T fusion reaction",
        "copilot",
        "2026-03-17",
    ),
    (
        "dd-reaction",
        "internal:expansion:batch-21",
        "D-D fusion reaction",
        "copilot",
        "2026-03-17",
    ),
    (
        "d-he3-reaction",
        "internal:expansion:batch-21",
        "D-He3 advanced fuel reaction",
        "copilot",
        "2026-03-17",
    ),
    (
        "fusion-triple-product",
        "internal:expansion:batch-21",
        "n*T*tau ignition metric",
        "copilot",
        "2026-03-17",
    ),
    # 14mev-neutron: evidence skipped — merged into existing fusion-neutron concept
    (
        "neutron-yield",
        "internal:expansion:batch-21",
        "Fusion neutron production rate",
        "copilot",
        "2026-03-17",
    ),
    (
        "reaction-rate-coefficient",
        "internal:expansion:batch-21",
        "Maxwellian-averaged reactivity",
        "copilot",
        "2026-03-17",
    ),
    (
        "q-value-reaction",
        "internal:expansion:batch-21",
        "Reaction energy release",
        "copilot",
        "2026-03-17",
    ),
    (
        "coulomb-logarithm",
        "internal:expansion:batch-21",
        "Collision frequency log factor",
        "copilot",
        "2026-03-17",
    ),
    (
        "slowing-down-time",
        "internal:expansion:batch-21",
        "Fast ion thermalization time",
        "copilot",
        "2026-03-17",
    ),
    (
        "current-hole",
        "internal:expansion:batch-22",
        "Central zero current region",
        "copilot",
        "2026-03-17",
    ),
    (
        "internal-kink-mode",
        "internal:expansion:batch-22",
        "m=1/n=1 internal instability",
        "copilot",
        "2026-03-17",
    ),
    (
        "sawtooth-crash",
        "internal:expansion:batch-22",
        "Periodic central profile crash",
        "copilot",
        "2026-03-17",
    ),
    (
        "ntv",
        "internal:expansion:batch-22",
        "Non-axisymmetric braking torque",
        "copilot",
        "2026-03-17",
    ),
    (
        "intrinsic-rotation",
        "internal:expansion:batch-22",
        "Spontaneous plasma rotation",
        "copilot",
        "2026-03-17",
    ),
    (
        "momentum-transport",
        "internal:expansion:batch-22",
        "Angular momentum transport",
        "copilot",
        "2026-03-17",
    ),
    (
        "profile-stiffness",
        "internal:expansion:batch-22",
        "Critical gradient transport",
        "copilot",
        "2026-03-17",
    ),
    (
        "critical-gradient",
        "internal:expansion:batch-22",
        "Instability threshold gradient",
        "copilot",
        "2026-03-17",
    ),
    (
        "fully-non-inductive",
        "internal:expansion:batch-22",
        "100% non-inductive steady state",
        "copilot",
        "2026-03-17",
    ),
    (
        "steady-state-high-beta",
        "internal:expansion:batch-22",
        "Advanced tokamak target",
        "copilot",
        "2026-03-17",
    ),
    (
        "ac-loss",
        "internal:expansion:batch-23",
        "Superconductor AC heating",
        "copilot",
        "2026-03-17",
    ),
    (
        "strain-sensitivity",
        "internal:expansion:batch-23",
        "Nb3Sn strain-Ic relation",
        "copilot",
        "2026-03-17",
    ),
    (
        "joint-resistance",
        "internal:expansion:batch-23",
        "SC cable joint resistance",
        "copilot",
        "2026-03-17",
    ),
    (
        "tf-ripple",
        "internal:expansion:batch-23",
        "Finite TF coil field variation",
        "copilot",
        "2026-03-17",
    ),
    (
        "demountable-joint",
        "internal:expansion:batch-23",
        "Separable HTS joint",
        "copilot",
        "2026-03-17",
    ),
    (
        "magnet-bore",
        "internal:expansion:batch-23",
        "TF coil inner opening",
        "copilot",
        "2026-03-17",
    ),
    (
        "winding-pack",
        "internal:expansion:batch-23",
        "SC cable turn assembly",
        "copilot",
        "2026-03-17",
    ),
    (
        "magnet-structure",
        "internal:expansion:batch-23",
        "Coil casing and support",
        "copilot",
        "2026-03-17",
    ),
    (
        "insulation-material",
        "internal:expansion:batch-23",
        "Magnet electrical insulation",
        "copilot",
        "2026-03-17",
    ),
    (
        "magnet-cooling",
        "internal:expansion:batch-23",
        "SC magnet cryogenic cooling",
        "copilot",
        "2026-03-17",
    ),
    (
        "chemical-erosion",
        "internal:expansion:batch-24",
        "Carbon chemical sputtering",
        "copilot",
        "2026-03-17",
    ),
    (
        "physical-sputtering",
        "internal:expansion:batch-24",
        "Ion bombardment erosion",
        "copilot",
        "2026-03-17",
    ),
    (
        "dust",
        "internal:expansion:batch-24",
        "PFC-generated particulates",
        "copilot",
        "2026-03-17",
    ),
    (
        "arcing",
        "internal:expansion:batch-24",
        "Plasma-wall arc discharge",
        "copilot",
        "2026-03-17",
    ),
    (
        "melt-damage",
        "internal:expansion:batch-24",
        "PFC transient melting",
        "copilot",
        "2026-03-17",
    ),
    (
        "mixed-material",
        "internal:expansion:batch-24",
        "Multi-material co-deposition",
        "copilot",
        "2026-03-17",
    ),
    (
        "wall-conditioning",
        "internal:expansion:batch-24",
        "Wall surface preparation",
        "copilot",
        "2026-03-17",
    ),
    (
        "glow-discharge-cleaning",
        "internal:expansion:batch-24",
        "GDC wall cleaning",
        "copilot",
        "2026-03-17",
    ),
    (
        "boronization",
        "internal:expansion:batch-24",
        "Boron film wall treatment",
        "copilot",
        "2026-03-17",
    ),
    (
        "tritium-removal",
        "internal:expansion:batch-24",
        "Retained tritium removal",
        "copilot",
        "2026-03-17",
    ),
    (
        "fokker-planck-equation",
        "internal:expansion:batch-25",
        "Collisional kinetic equation",
        "copilot",
        "2026-03-17",
    ),
    (
        "vlasov-equation",
        "internal:expansion:batch-25",
        "Collisionless kinetic equation",
        "copilot",
        "2026-03-17",
    ),
    (
        "ray-tracing",
        "internal:expansion:batch-25",
        "Wave propagation computation",
        "copilot",
        "2026-03-17",
    ),
    (
        "flux-tube-simulation",
        "internal:expansion:batch-25",
        "Local GK simulation domain",
        "copilot",
        "2026-03-17",
    ),
    (
        "reduced-mhd",
        "internal:expansion:batch-25",
        "Simplified low-beta MHD",
        "copilot",
        "2026-03-17",
    ),
    (
        "extended-mhd",
        "internal:expansion:batch-25",
        "Two-fluid extended MHD",
        "copilot",
        "2026-03-17",
    ),
    (
        "two-fluid-model",
        "internal:expansion:batch-25",
        "Electron-ion fluid model",
        "copilot",
        "2026-03-17",
    ),
    (
        "delta-f-method",
        "internal:expansion:batch-25",
        "PIC noise reduction",
        "copilot",
        "2026-03-17",
    ),
    (
        "full-f-method",
        "internal:expansion:batch-25",
        "Full distribution PIC",
        "copilot",
        "2026-03-17",
    ),
    (
        "continuum-kinetic",
        "internal:expansion:batch-25",
        "Vlasov grid discretization",
        "copilot",
        "2026-03-17",
    ),
    (
        "defense-in-depth",
        "internal:expansion:batch-26",
        "Multi-layer safety philosophy",
        "copilot",
        "2026-03-17",
    ),
    (
        "safety-classification",
        "internal:expansion:batch-26",
        "System safety categorization",
        "copilot",
        "2026-03-17",
    ),
    (
        "iaea",
        "internal:expansion:batch-26",
        "UN nuclear agency",
        "copilot",
        "2026-03-17",
    ),
    (
        "confinement-function",
        "internal:expansion:batch-26",
        "Radioactive containment barrier",
        "copilot",
        "2026-03-17",
    ),
    (
        "maximum-credible-accident",
        "internal:expansion:batch-26",
        "Worst-case safety scenario",
        "copilot",
        "2026-03-17",
    ),
    (
        "source-term",
        "internal:expansion:batch-26",
        "Accident release quantification",
        "copilot",
        "2026-03-17",
    ),
    (
        "emergency-planning-zone",
        "internal:expansion:batch-26",
        "Emergency response area",
        "copilot",
        "2026-03-17",
    ),
    (
        "occupational-dose-limit",
        "internal:expansion:batch-26",
        "Worker annual dose limit",
        "copilot",
        "2026-03-17",
    ),
]


def write_tsv_rows(path, rows):
    with open(path, "a", encoding="utf-8") as f:
        for row in rows:
            if len(row) == 1:
                f.write(row[0] + "\n")
            else:
                f.write(T.join(row) + "\n")


if __name__ == "__main__":
    write_tsv_rows(REG / "concepts.tsv", CONCEPTS)
    n_c = sum(1 for r in CONCEPTS if len(r) > 1)
    print(f"Appended {n_c} concepts")

    write_tsv_rows(REG / "aliases.tsv", ALIASES)
    n_a = sum(1 for r in ALIASES if len(r) > 1)
    print(f"Appended {n_a} aliases")

    write_tsv_rows(REG / "evidence.tsv", EVIDENCE)
    print(f"Appended {len(EVIDENCE)} evidence rows")
